In [20]:
#####################################################################################################################################
##### This script evaluates the performance of the LemonIte network against PKN
##### This will be done in two different approaches:
#####       1. Classic evaluation metrics (accuracy, precision, recall, F1-score) of LemonIte network against the ground truth data
#####       2. Evaluation of average shortest paths for metabolite-gene pairs from LemonIte network in the PKN
#####################################################################################################################################

In [21]:
# import modules and set working directory
import os
import pandas as pd
import numpy as np
import networkx as nx
from multiprocessing import Pool
from scipy.stats import hypergeom
from adjustText import adjust_text
import matplotlib.pyplot as plt
import seaborn as sns

os.chdir('/home/borisvdm/Documents/PhD/thesis_Mirte/Wang2021/results/LemonTree/noProteomics_percentile2/')

percentile = 2
n_modules = '46'

workdir = os.getcwd()


dataset_file = workdir + f'/Preprocessing/LemonPreprocessed_complete.txt'
lemonnetwork_file = workdir + f'/Networks/LemonNetwork_percentile{percentile}_{n_modules}modules.txt'
PKNnetwork_file = '/home/borisvdm/Documents/PhD/Lemonite/PKN/LemonIte_PKN.tsv'
annotated_mets = workdir+ f'/Preprocessing/name_map.csv' # paste metabolite list in MetaboAnalyst id mapping tool and download result + manually look into annotations
#metabolite_interactions_file = workdir + f'/PKN/HMDB_metabolites_gene_interactions.tsv'


TF_regulator_file = workdir+'/ModuleViewer_files/Lovering.percentile'+str(percentile)+'_list.txt'
metabolite_regulator_file = workdir+'/ModuleViewer_files/Metabolite.percentile'+str(percentile)+'_list.txt'
#metabolite_random_regulator_file = workdir+'ModuleViewer_files/Metabolite.randomreg_list.txt'
clusterfile = workdir+'/Lemon_out/clusters_list.txt'
metabolite_interactions_file = '/home/borisvdm/Documents/PhD/Lemonite/PKN/HMDB_metabolites_gene_interactions.csv'

# Read predicted network and create some dictionaries to map modules to genes, regulators to genes, etc

In [22]:
lemonnetwork = pd.read_csv(lemonnetwork_file, sep='\t')
lemonnetwork
lemonnetwork_metabolites = lemonnetwork[lemonnetwork['Type'] == 'Metabolite-gene']
print(lemonnetwork_metabolites)
# create dict with metabolite-gene interactions
metabolites2genes = {}
for index, row in lemonnetwork_metabolites.iterrows():
    if row['Regulator'] not in metabolites2genes:
        metabolites2genes[row['Regulator']] = [row['Target']]
    else:
        metabolites2genes[row['Regulator']].append(row['Target'])

genes_in_dataset = lemonnetwork['Target'].unique()
print(f'There are {len(genes_in_dataset)} genes in the dataset')

        Regulator  Target      Score  Lemon_module             Type
9969   creatinine  VSTM2L  64.743192             0  Metabolite-gene
9970   creatinine  GABRA5  64.743192             0  Metabolite-gene
9971   creatinine    SYT4  64.743192             0  Metabolite-gene
9972   creatinine   CREG2  64.743192             0  Metabolite-gene
9973   creatinine  SYNGR3  64.743192             0  Metabolite-gene
...           ...     ...        ...           ...              ...
14982  L_cysteine   NXPH3  13.740352            62  Metabolite-gene
14983  L_cysteine  COL9A1  13.740352            62  Metabolite-gene
14984  L_cysteine    GAD1  13.740352            62  Metabolite-gene
14985  L_cysteine  FRMPD1  13.740352            62  Metabolite-gene
14986  L_cysteine  SMIM18  13.740352            62  Metabolite-gene

[5018 rows x 5 columns]
There are 1930 genes in the dataset

In [23]:
# Funtion to create a dictionary with all regulators per module (start from the regulators.fold file created using LemonTree_downstream.py)
def get_regulators(regfile):
    regs = {}
    with open(regfile) as f:
        for line in f:
            module = line.split('\t')[0]
            regulators = line.rstrip().split('\t')[1].split('|')
            regs[module] = regulators
    return regs

module2TFs = get_regulators(TF_regulator_file)
module2mets = get_regulators(metabolite_regulator_file)
module2genes = get_regulators(clusterfile)
#module2mets_random = get_regulators(metabolite_random_regulator_file)

print('modules:', module2genes)
print('TFs:', module2TFs)
print('mets:', module2mets)
#print('mets_random:', module2mets_random)

modules: {'0': ['VSTM2L', 'GABRA5', 'SYT4', 'CREG2', 'SYNGR3', 'RBFOX1', 'KCNS1', 'SYP', 'GPR83', 'PRSS3', 'STX1B', 'TGFBR3L', 'GLT1D1', 'AK5', 'SPTB', 'C4orf50', 'VIPR1', 'TMEM130', 'IQSEC3', 'SYN1', 'CHD5', 'GREM2', 'SYT7', 'PRMT8', 'KCNJ4', 'HPCAL4', 'GABRD', 'ADAM11', 'EPHB6', 'KCTD16', 'GALNTL6', 'RASAL1', 'SLC17A7', 'CPLX1', 'DOC2A', 'GPR61', 'PACSIN1', 'GABRB2', 'PCP4L1', 'ARHGDIG', 'TMEM155', 'CABP1', 'CAMK2A', 'NRGN', 'DLGAP3', 'SNAP25', 'DDN', 'MTUS2', 'CACNA1B', 'GNG3', 'MPPED1', 'SLC6A17', 'SNCB', 'SLC6A7', 'SLC8A2', 'VWA5B2', 'PPP2R2C', 'SV2C', 'CALY', 'SLC30A3', 'SLC12A5', 'HPCA', 'NEFM', 'MAS1', 'CPNE6', 'C1QTNF4', 'UNC5A', 'AJAP1', 'SYT5', 'MFSD4', 'STYK1', 'GLS2', 'KIAA1644', 'ICAM5', 'ATP8A2', 'NEURL1', 'KIAA1045', 'ATP2B3', 'SYN2', 'CAMK1G', 'CRYM', 'MAP7D2', 'PHYHIP', 'FSTL4', 'TRHDE', 'RTN4RL1', 'PSD', 'RYR2'], '1': ['GAD2', 'CACNG3', 'GJD2', 'NWD2', 'PCSK2', 'SYNPR', 'GABRG2', 'WSCD2', 'FADS6', 'GABRG3', 'KLHL1', 'CCK', 'GPR26', 'MYT1L', 'EPHA6', 'LRTM2', 'HCN1', 'SLC32A1', 'GRIN1', 'C1QL3', 'KCNV1', 'HTR5A', 'FRMPD4', 'SOHLH1', 'AMER3', 'TCERG1L', 'CDH18', 'KCNB2', 'CDH9', 'CHRM1', 'SSTR3', 'FAM153C', 'SVOP', 'KCNT1', 'KCNS2', 'CELF4', 'KCNJ3', 'CHRM2', 'GPR22', 'CPLX2', 'MAL2', 'HTR2A', 'FAM163B', 'CDH12', 'TMEM132D', 'VSNL1', 'SYT1', 'NEFL', 'PTPN5', 'UNC13C', 'SYT13', 'MCHR2', 'DLGAP2', 'CA7', 'GABRA4', 'OLFM3', 'EMX1', 'SV2B', 'RBFOX3', 'CCKBR', 'SLC35F3', 'CHGA', 'DNAJC5G', 'GABRA1', 'LYPD8', 'SULT4A1', 'KCNC2', 'CBLN2', 'FAM153B', 'INA', 'ANKRD30B'], '2': ['REPS2', 'VSTM2B', 'RIMS2', 'HMGCLL1', 'LINGO2', 'SAMD12', 'DACH2', 'FSTL5', 'FGF13', 'KCNH1', 'CDKL2', 'FRRS1L', 'KCNA1', 'LRFN5', 'SLITRK1', 'NDST3', 'ZNF385B', 'IQCJ', 'DRD1', 'NAP1L2', 'CNTN3', 'ANKRD18B', 'SPHKAP', 'ERC2', 'GRIN2A', 'SSTR1', 'CNTNAP2', 'ANK3', 'AMPH', 'KCTD4', 'BEND4', 'PAK7', 'GABRB3', 'ADAMTS19', 'SLC7A14', 'KCNA4', 'GLRA3', 'PRLHR', 'RIMS1', 'CNNM1', 'SNAP91', 'NOS1', 'ANKRD30BL', 'ATRNL1', 'LRRC7', 'WBSCR17', 'PNMA5', 'SGCZ', 'KHDRBS2', 'RALYL', 'MUM1L1', 'RUNDC3B', 'TCEAL6', 'SLITRK4', 'HS3ST4', 'CNTN4', 'GNAL', 'KSR2', 'CLVS2', 'STXBP5L', 'SLC1A6', 'TMEM246', 'GABRG1', 'ANO3', 'KCNK1', 'KCNK12', 'GRM5', 'ANKS1B', 'MGAT4C', 'PCDH11X', 'MTMR7', 'GABRA3', 'ELAVL2', 'CBLN1', 'CSMD3', 'NEGR1', 'RXFP1', 'HPSE2', 'ADARB2', 'DOK6', 'KCNJ9', 'DPP10', 'SLC6A15'], '3': ['SPEF1', 'CFAP54', 'ZBBX', 'HYDIN', 'KIAA1257', 'CATIP', 'MAK', 'RSPH1', 'CCDC65', 'DNAAF1', 'SLC9C2', 'C1orf158', 'DRC7', 'PRR29', 'WDR38', 'ROPN1L', 'WDR63', 'TEKT1', 'CFAP43', 'CCDC37', 'ZMYND10', 'MORN5', 'VWA3A', 'CFAP57', 'LRRC74B', 'CFAP52', 'SDR42E2', 'DNAAF3', 'RSPH4A', 'DRC1', 'DNAH5', 'DNAH6', 'WDR93', 'C6orf118', 'MAP3K19', 'C9orf171', 'DNAI1', 'DTHD1', 'C1orf194', 'VWA3B', 'TCTEX1D1', 'C7orf57', 'CCDC42B', 'DCDC1', 'RP11-723O4.6', 'ANKRD45', 'DNAH7', 'EFCAB10', 'CFAP99', 'CFAP126', 'EFHC2', 'NEK5', 'C9orf117'], '4': ['GPD1', 'AATK', 'CDH19', 'CTNNA3', 'SYT9', 'GREM1', 'PTGDS', 'ASPA', 'S1PR5', 'JAKMIP3', 'KLHL32', 'ZNF536', 'EDIL3', 'HS3ST5', 'DNAH17', 'ABHD12B', 'FAM178B', 'TMEM144', 'ENPP2', 'PDIA2', 'PRCD', 'HCN2', 'ANO4', 'SLC24A2', 'CD22', 'SPAG6', 'C10orf90', 'EFHD1', 'TLL2', 'HHIP', 'SRCIN1', 'TRPV6', 'FOLH1', 'CHADL', 'OR9A2', 'BCAS1', 'ENPP6', 'PPP1R14A', 'S100A1', 'PLCH2', 'RASGRF1', 'LRRC63', 'PLLP', 'SH3TC2', 'GPIHBP1', 'TRPV5', 'UGT8', 'NRIP2', 'PCSK6', 'CLDN11', 'SLCO1A2', 'PPAP2C', 'TRPM6', 'GRM3', 'USH1C', 'KANK4', 'TP53TG5', 'PPP1R16B', 'PAIP2B', 'BOK'], '5': ['ANPEP', 'STC1', 'SAA2', 'OSM', 'HP', 'CXCL1', 'PTGS2', 'CD300E', 'CXCL5', 'IL1A', 'CCL20', 'SAA1', 'C15orf48', 'PTX3', 'SLC39A8', 'CXCL8', 'LILRB3', 'IL1B', 'TNFAIP2', 'AQP9', 'G0S2', 'IL24', 'HCAR3', 'NAMPT', 'SAA2-SAA4', 'IL36RN', 'TGFBI', 'CCL7', 'LILRA5', 'HCAR2', 'TREML2', 'IL1RN', 'CYR61', 'SOCS3', 'IL32', 'IER3', 'MCEMP1', 'FPR2', 'MMP19', 'TNFSF14', 'BCL2A1', 'LIF', 'PI3', 'CSF3', 'PLIN2', 'HSPA6', 'IL6', 'LILRA6', 'THBD', 'PLAUR', 'CCL2', 'HSD11B1', 'CHI3L2', 'S100A9', 'BDKRB2', 'SLC16A10', 'ADAM8', 'CXCL2', 'THBS1', 'SOD2', 'TREM1', 'BIRC3', 'CFB', 'FCAR', 'CXCL3', 'ICAM1'], '6': ['JPH3', 'RUNDC3A', 'JAKMIP1', 'CCDC64', 'RBP4', 'ZCCHC12', 'CCDC177', 'BSN', 'SH3GL2', 'SLC27A2', 'PRKCG', 'PPP1R1A', 'RSPO3', 'RAP1GAP', 'ASPDH', 'RELN', 'PRKCZ', 'RTN4RL2', 'B3GNT4', 'ATCAY', 'DYNC1I1', 'JPH4', 'FAM19A1', 'MARCHF4', 'GLB1L3', 'SERPINI1', 'KIAA0319', 'SPTBN2', 'CELF5', 'CHRNB2', 'SLC26A8', 'FBXL16', 'CKMT1A', 'CACNA1I', 'NPTX1', 'CCBE1', 'ISLR2', 'CELF3', 'BSPRY', 'SOWAHB', 'POU6F2', 'MCF2', 'CHRNA4', 'CA4', 'KIF1A', 'SHANK1', 'PDE1A', 'CYP4X1', 'GRM1', 'GRIN2B', 'GRM4', 'SYT2', 'TESPA1', 'ELFN2', 'HS3ST2', 'CACNA1E', 'CCSER1', 'ACTL6B', 'SRRM3', 'CACNA2D3', 'KCNJ12', 'NYAP2', 'NMNAT2', 'ZFR2', 'GDA', 'DRD5', 'STMN2', 'SMPD3', 'NPM2', 'TMEM151B', 'GRIN3A', 'UBE2QL1', 'CRHBP', 'CDH8', 'LPPR3', 'KCNK3', 'ZNF831', 'PTPRR', 'RAB3C', 'XKR7', 'NELL1', 'KCNH5', 'MPP7', 'BEX5', 'PAK3', 'CHGB', 'LY6H', 'NEFH', 'OLFM1', 'SCN2B', 'COL26A1', 'SIAH3', 'SGSM1', 'SLC17A6', 'HECW1', 'CAMKV', 'RTN4R', 'CUX2', 'PRDM8', 'WNT10B', 'TMEM196', 'STAR', 'DUSP26', 'GRM2', 'ACVR1C', 'GRIP1', 'SYT16', 'RIMBP2', 'CALN1', 'GLP2R', 'ST8SIA3', 'CKMT1B', 'SRRM4', 'SHANK2', 'RGS7', 'CAMSAP3', 'KIRREL3', 'HOOK1', 'CDK5R1', 'PRRG3', 'SCRT1', 'GALNT9', 'HMP19', 'BRINP1', 'KCNH3', 'SHISA7', 'TAGLN3', 'LRFN2', 'ENTPD3', 'OPCML', 'GRM7', 'GDAP1L1', 'SOWAHA', 'DOC2B', 'CDH22', 'ATP1A3', 'ELAVL4', 'NECAB2', 'EPHA10', 'PNMA3', 'PPP4R4', 'SSTR2', 'PDE2A', 'CES4A', 'CPNE7', 'SNCG', 'SCN3B', 'SNCA', 'HRH3', 'ADRA2C', 'SYN3', 'SLC4A10', 'OVOL2', 'SEPTIN3', 'TTC9B'], '7': ['TNFRSF11B', 'P4HA3', 'KCNK15', 'HAS3', 'CFI', 'MET', 'ARHGEF5', 'ACTG2', 'PTGIS', 'ADAMTS14', 'COL15A1', 'LTBP2', 'LCTL', 'GCNT1', 'MLPH', 'ASPN', 'RARRES1', 'STEAP1', 'CYP1B1', 'CD109', 'BNC2', 'CHI3L1', 'PODNL1', 'PLAU', 'ITGBL1', 'C3orf52', 'ISLR', 'KRT8', 'KRT18', 'MGP', 'COL14A1', 'TIMP1', 'COL12A1', 'SLPI', 'ALDH1A3', 'SCNN1A', 'ZCCHC5', 'SRPX2', 'MXRA5', 'ADAMTS2', 'PDGFRL', 'COL13A1', 'CATSPERB', 'ANO1', 'TSLP', 'AVPR1A', 'EGFL6', 'INHBA', 'LRRC8E', 'MMP9', 'COL6A3', 'PLA1A', 'FAM46B', 'PRLR', 'DCN', 'SPOCD1', 'EFEMP1', 'PAPPA', 'ITGA8', 'CHRNA9', 'DKK1', 'EMP3', 'CXCL14', 'SEL1L3', 'COL1A1', 'STRA6', 'KRT7', 'RFX8', 'PHLDA2', 'TC2N', 'TFPI2', 'CYGB', 'MYBPH', 'PTGES', 'C8orf4', 'SERPINE1', 'MEDAG', 'CP', 'C1S', 'PLA2R1', 'DSG2', 'SDC1', 'PCOLCE', 'PTPRU', 'CCDC71L', 'CAV2', 'PLEKHN1', 'GPX8', 'VGLL3', 'HTRA3', 'LUM', 'LOXL4', 'GALNT5', 'AHNAK2', 'KCNN4', 'FCN3', 'IGFBP6', 'GDF15', 'COL3A1', 'SMAGP', 'CAV1', 'COL1A2', 'COL8A1', 'COL6A2', 'SGMS2', 'ABCA13', 'COL5A1', 'PRKCDBP', 'KDELR3', 'TAGLN', 'CTHRC1', 'FAM83G', 'GJB2', 'CFH', 'CD274', 'ABCC3', 'CLCF1', 'CNN1', 'HES2', 'RAB38', 'FAP', 'IL11', 'CLDN23', 'MMP11', 'ITGA3', 'FOXS1', 'C6orf141', 'FBLN2', 'CLDN1'], '8': ['OPALIN', 'HAPLN2', 'LGI3', 'KLK6', 'MBP', 'CARNS1', 'FA2H', 'GPR62', 'TPPP', 'HHATL', 'TMEM125', 'TMEM151A', 'SH3GL3', 'NKAIN2', 'TMEM88B', 'PEX5L', 'CNDP1', 'ST18', 'GJB1', 'MOG', 'SPOCK3', 'TF', 'CNTNAP4', 'MAG', 'PLP1', 'ERMN', 'TMEM235', 'LRP2', 'CLCA4', 'MOBP', 'SLC5A11', 'LDB3', 'CNTN2', 'ANKRD18A', 'SEC14L5', 'NKX6-2', 'MAL'], '9': ['ZDHHC22', 'SLIT1', 'GRIA2', 'DGKB', 'NRXN2', 'COL20A1', 'ELAVL3', 'NEU4', 'DCAF4L2', 'KCNQ2', 'BRSK2', 'WSCD1', 'KCNA2', 'ADD2', 'EFNA2', 'C1orf61', 'MPPED2', 'CACNG4', 'PIANP', 'RNF165', 'NCALD', 'TNR', 'NTRK3', 'NKAIN4', 'BAI1', 'BTBD17', 'CSPG5', 'NLGN3', 'LHFPL3', 'LRRTM2', 'UNC13A', 'CNTNAP5', 'BCHE', 'SAPCD2', 'MGAT5B', 'SOX8', 'ONECUT2', 'PTPRD', 'TAC4', 'CACNG7', 'FAM181B', 'TMEM145', 'MEX3A', 'ASIC4', 'FHDC1', 'NPPA', 'NRXN1', 'SCG3', 'XKR5', 'SNTG1', 'FXYD6', 'GRIK3', 'LRRTM3', 'FAM131B', 'THSD7A', 'SLC5A12', 'ZBTB8B', 'BCAN', 'SCRT2', 'FGF14', 'SBK1', 'CDHR1', 'GSX1', 'TRIM71', 'DIRAS2', 'MMD2', 'PTCHD2', 'MMP16', 'BEX1', 'PRR36', 'C2orf80', 'FAM19A5', 'DCX', 'LHFPL4', 'LPPR5', 'TMEM132B', 'CRB1', 'GPR45', 'LINGO1', 'GPC2', 'FLRT1', 'GPR12', 'MAST1', 'RTP5', 'LMO1', 'CCER2', 'SEZ6L', 'ROBO2', 'GNG4', 'SCN3A', 'SHD', 'DLL3', 'FAM57B', 'CACNG8', 'CNTFR', 'MAP2', 'TNFRSF13C', 'DSCAM', 'RGR', 'GPR123', 'SLC18A1', 'FBN3', 'SEMA5B', 'ARHGAP19-SLIT1', 'NXPH1', 'CSMD1'], '10': ['LCK', 'TIGIT', 'NKG7', 'SLFN12L', 'GZMK', 'CXCR6', 'GRAP2', 'CD8B', 'GZMA', 'CD3D', 'CRTAM', 'FASLG', 'SH2D1A', 'SIT1', 'CD5', 'GZMH', 'ANO9', 'SLAMF6', 'SKAP1', 'GPR174', 'SLAMF7', 'CD2', 'CD3E', 'CCR4', 'CST7', 'CXCR3', 'ICOS', 'PDCD1', 'EPHA1', 'P2RY10', 'CD27', 'THEMIS', 'CD52', 'SAMD3', 'CD8A', 'IL2RB', 'APOBEC3H', 'CD3G', 'CD6', 'PYHIN1', 'CCL5', 'CD96', 'TRAT1', 'UBASH3A'], '11': ['MSMP', 'ZDHHC23', 'ADRA1D', 'SHROOM3', 'JPH1', 'LAMA2', 'KCTD14', 'ZIC5', 'TFCP2L1', 'TRPM3', 'CPNE4', 'ACSS3', 'RASEF', 'PLA2G5', 'ARSF', 'C6orf15', 'COL25A1', 'PKIB', 'LGR6', 'GPR37', 'ALK', 'PSORS1C1', 'COL23A1', 'TMEM221', 'NOS2', 'EYA4', 'ADAMTS18', 'STAC', 'TSTD1', 'ADAMTS3', 'LANCL3', 'HABP2', 'DBX2', 'DPP4', 'NPNT', 'MT1E', 'LIPC', 'DMRTA2', 'CMYA5', 'SLC16A11', 'SRPX', 'OPLAH'], '12': ['TMEM132C', 'ERBB4', 'NRXN3', 'CYS1', 'CADPS', 'ZNF727', 'COL11A1', 'NPFFR1', 'BMP6', 'PHACTR3', 'FAM196B', 'MCF2L2', 'PRSS35', 'NPY1R', 'CNTN1', 'SYT14', 'FUT9', 'ZNF98', 'RIPPLY2', 'TCEAL2', 'ARHGAP36', 'GDNF', 'CACNA2D1', 'CXorf57', 'RPS6KA6', 'FREM3', 'LUZP2', 'SMOC1', 'GREB1L', 'FGF12', 'CSDC2', 'SLC25A21', 'DLGAP1', 'TRDN', 'FAM155B', 'LRRTM4', 'ZNF676', 'ADAM29', 'TACR1', 'ACTRT3', 'FGF9', 'CYP7B1', 'PARM1', 'GFRA1', 'AFF2', 'ANO5', 'CRTAC1', 'LRRTM1', 'AIM2', 'SLIT2', 'ASB2', 'GALNT13', 'SLC16A7', 'GRID2', 'TLL1', 'TTC6', 'GHR', 'MIPOL1', 'AKR1C3', 'RANBP17', 'HMX1', 'TRIM67', 'CYP26B1', 'MYO3A', 'CLGN', 'ZNF99', 'PABPC5', 'PDE11A', 'PLCXD3', 'NAV3', 'ASB4', 'SEMA3D', 'KCNH8', 'NDST4', 'SLC44A5', 'CADM3', 'BAMBI', 'TRAM1L1', 'PRKG2', 'MACROD2', 'KIAA1324L', 'KIAA2022', 'C3orf67', 'NDN', 'PCDHA2', 'EPB41L4B', 'PCBP3', 'PIK3C2G', 'GFRA2', 'FAM155A', 'PCDHA1', 'ADAMTS16', 'ADAMTSL3', 'SLITRK6', 'SVIP', 'GABBR2', 'BRINP3', 'CA10', 'TENM3', 'TRIM17', 'GIPR', 'CACNA1A', 'ZNF492', 'SLITRK5', 'EPHA7', 'RAB27B', 'EXO5', 'PCDH7', 'PPFIA2', 'OTOGL', 'TUSC3', 'ARHGAP28', 'VAT1L', 'ARPP21', 'CDH13', 'NALCN', 'MYH14', 'PPAPDC1A', 'RCAN2', 'VWC2', 'RNF212', 'TMEM35', 'SYNDIG1L', 'ZNF208', 'B3GALT2', 'RPRM', 'SGCD', 'SUSD5', 'KCNB1', 'FAM135B', 'FAM133A', 'AKR1C1', 'DNER', 'NETO1', 'NCAM2', 'KCNQ5', 'ZNF804B', 'DRP2', 'PTGER3', 'C5orf38', 'ZC3H12B', 'NUDT10', 'MLIP', 'CCDC85A'], '13': ['GPR84', 'LTB', 'IL7R', 'IL4I1', 'FOLR2', 'CR1', 'RNASE2', 'IL2RA', 'CD28', 'CD163', 'PRF1', 'S100A8', 'AMICA1', 'FPR3', 'VSIG4', 'KMO', 'PTGDR', 'ADTRP', 'LY9', 'F13A1', 'FAM20A', 'ACP5', 'TLR8', 'SLC11A1', 'CD300LB', 'CD36', 'FPR1', 'IL1R1', 'IL18R1', 'SERPINA1', 'LILRB5', 'SLAMF8', 'GPR183', 'MRC1', 'CCR2', 'CCL8', 'FCGR2B', 'ACPP', 'DNAJC5B', 'SPHK1', 'CLEC10A', 'GPNMB', 'DOK2', 'ASGR2', 'HK3', 'PTGER2', 'LRG1', 'TMEM150B', 'SELE', 'IL10', 'TNFSF15', 'NXF3', 'EREG', 'RHOH', 'CFD', 'MCTP2', 'EVA1A', 'P2RY8', 'TNFRSF9', 'LYZ', 'LYVE1'], '14': ['CTXN3', 'TRPC5', 'TACR3', 'CLEC2L', 'ASIC2', 'HTR1E', 'TMEM215', 'SDR16C5', 'HS6ST3', 'PABPC1L2B', 'LHFPL5', 'GALNTL5', 'FAM153A', 'WIF1', 'CYP4Z1', 'MARCHF11', 'SST', 'PNPLA5', 'OCA2', 'SYCE1', 'LCN15', 'MYADML2', 'RPRML', 'KLK7', 'PPP3R2', 'RTBDN', 'GPR149', 'CARTPT', 'CHRNA2', 'SLC22A10', 'CRHR2', 'OPRM1', 'GABRA2', 'CNTN5', 'PABPC1L2A', 'NGB', 'TNNT2', 'SLC7A4', 'GJB5', 'FBXO40', 'C11orf87', 'HTR2C', 'CALHM1', 'SERTM1', 'ANKRD34C', 'HTR3B', 'EIF4E1B', 'KCNG3'], '15': ['FAM181A', 'C2orf50', 'PIRT', 'ALDH3A1', 'PLA2G2A', 'GPR1', 'C11orf63', 'TRIM29', 'HPD', 'RAMP3', 'TMIE', 'SCNN1G', 'TXLNB', 'ANKK1', 'MAOB', 'FER1L5', 'C20orf195', 'ABCA5', 'FOLR1', 'HRASLS5', 'DNAH9', 'LRRC9', 'GCOM1', 'EVC2', 'DDIT4L', 'FAM160A1', 'SCNN1B', 'SPAG17', 'HSPB7', 'SLC47A2', 'FLNC', 'TPPP3', 'CFAP45', 'LRRC2', 'RARRES2', 'F3', 'VASN', 'MYZAP', 'C15orf26', 'GSX2', 'FAM65C'], '16': ['AMIGO2', 'IGSF3', 'ALDOC', 'ABCD2', 'CCDC129', 'FAM196A', 'PPP1R1C', 'PSD2', 'CHRM3', 'CLDN10', 'COL4A6', 'A2ML1', 'C4orf19', 'NDRG2', 'ST6GAL2', 'TMEM74', 'PAH', 'KCNIP1', 'TUSC1', 'RLBP1', 'ATP1A2', 'ART3', 'RNF148', 'WIPF3', 'RGS9', 'ADCYAP1R1', 'ENPP5', 'ENDOU', 'SLC24A4', 'C19orf81', 'KCNJ16', 'CAMK2B', 'DCHS2', 'ELOVL2', 'KCNN2', 'ENHO', 'LGI4', 'PVRL3', 'PHYHD1', 'WNT9B', 'KCNJ10', 'C1orf110', 'CDK6', 'TENM1', 'WNT7A', 'PI16', 'ATP13A5', 'MASP1', 'EDNRB', 'ALDH1L1', 'RGS6', 'PLIN5', 'C10orf105', 'DMKN', 'ATP1A4', 'NETO2', 'CNR1', 'ADAM33', 'GRAMD2', 'GOLGA7B', 'EFNA5', 'CHST8', 'ANGPT1', 'SLC1A2', 'NDNF', 'KIAA1456', 'LIX1', 'SLC24A3', 'VSX1', 'RORB', 'AIFM3', 'CYP4F11', 'WNT16', 'MT1M', 'DRAXIN', 'FREM2', 'BAIAP3', 'PHYHIPL', 'KIAA1377', 'ANKEF1', 'LAMA3', 'NCAN', 'AQP1', 'ETNPPL', 'UPP2', 'PALM2', 'ACSL6', 'ACOT12', 'MGST1', 'GMPR', 'LGI1', 'EMILIN3', 'GPR37L1', 'SOCS2', 'RET', 'GSG1L', 'MAPK4', 'TRIL', 'COL4A5', 'FAM69C', 'COL21A1', 'KLHL4', 'SPX', 'NKAIN3', 'IGSF1', 'C2orf66', 'CNGA3', 'DMRTA1', 'LMO3', 'FABP7', 'LINGO3', 'KIF19', 'GAS1', 'SHISA6', 'SLC6A11', 'CASQ1', 'SLC4A4', 'AC005477.1', 'STEAP2', 'TP53AIP1', 'RASSF9', 'ADRA2A', 'DAAM2', 'FAM189A2', 'SPEF2', 'RANBP3L', 'ARMC4', 'MT3', 'DGKG', 'PNPLA3', 'MYBPC1', 'SLITRK3', 'LRRC3B', 'HSPB8', 'NTSR2', 'FAM184B', 'ACKR4', 'SYDE2', 'PALM2-AKAP2', 'HPR', 'AGMO', 'FRMPD2', 'ST8SIA5', 'MAB21L1', 'PRODH', 'KCNF1', 'PON1', 'COL9A3', 'ADCY2', 'CDH4', 'RIMS4', 'CA14', 'FAM107A', 'SKIDA1', 'PTGDR2', 'ATP13A4', 'ACBD7', 'B3GAT2', 'AMER2', 'SLC14A1', 'FAT4', 'C11orf70', 'TAS2R7', 'CYP39A1', 'HAPLN4', 'SIDT1', 'GFAP', 'FAM19A3', 'IGF2BP3', 'PDZD2', 'SLC25A48', 'GYG2', 'PPP1R1B', 'NTRK2', 'LRAT', 'GRIK1', 'BEAN1', 'LMNTD1', 'PTPRQ', 'CDH20', 'CDH10', 'FXYD1', 'ACSBG1', 'NWD1', 'ARC', 'AGT', 'STK32B', 'AIF1L', 'ENPP4', 'TTPA', 'PEBP4', 'MEGF10', 'FGFR3', 'CD38', 'LHFPL1', 'GRIN2C', 'RPH3A', 'BMP7', 'FAT3'], '17': ['LPAR4', 'CYP27C1', 'RAB33A', 'SLC18A3', 'LRRC4C', 'PCDH15', 'RP11-35N6.1', 'KLRC4', 'NAT16', 'KCND2', 'LGR5', 'H2AFY2', 'IGF2', 'BMPER', 'CDH1', 'KLRK1', 'KLHL35', 'RASL11B', 'ARHGEF16', 'CPXM1', 'SCN5A', 'EDARADD', 'CDH3', 'WNT7B', 'MAP3K15', 'CHRNA3', 'ACAN', 'DGKI', 'ERBB3', 'KLRC2', 'POLR2F', 'EYS', 'SLC8A3', 'C1QL4', 'MDFI', 'SAMD11', 'KIF26A', 'D4S234E', 'MYO5B', 'SNX22', 'WDR86', 'LTK', 'AQP3', 'F12', 'GRIK2', 'PDGFRA', 'MYO3B', 'SORCS3', 'C1QL1', 'FAM222A', 'NPR3', 'DLK1', 'RGS8', 'GPR64', 'KLRC4-KLRK1', 'CMTM5', 'ULBP1', 'MEGF11', 'ELFN1', 'DACT2', 'OR4N2', 'GPR17', 'PODN', 'ATP6V0A4', 'MDGA2', 'DSCAML1', 'OXCT2', 'SYT6', 'LHX5', 'RP11-277P12.6', 'CYP21A2', 'LCNL1', 'VGF', 'MN1', 'BMP8B', 'KLRC3', 'ECEL1', 'MMP17', 'CABP7', 'B4GALNT3'], '18': ['ADAM12', 'LZTS1', 'KCNE4', 'LOXL1', 'IGFBP2', 'TNFAIP6', 'SCN9A', 'DHH', 'DUSP4', 'MUC12', 'GRB10', 'CPNE8', 'PDPN', 'HS3ST3B1', 'AZGP1', 'SCN7A', 'IL1RAP', 'UCN2', 'ARSJ', 'MCHR1', 'SLC52A1', 'INMT', 'PTCHD4', 'IGF2BP2', 'BCAT1', 'TGFA', 'TRPM8', 'RGS17', 'LGALS3', 'SPRY4', 'LIPH', 'SEC14L6', 'WISP1', 'EDA2R', 'FABP5', 'MDK', 'COL22A1', 'OCIAD2', 'POSTN', 'PTPRH', 'PDGFD', 'C1QTNF1', 'RYR3', 'NGFR', 'HS3ST3A1', 'DIRAS3', 'BDNF', 'PRG4', 'RAB34', 'SHH', 'SCG2', 'ELMOD1', 'CHL1', 'METTL7B', 'TMEM158', 'CCDC8', 'FMOD', 'GRIA1'], '19': ['ADGB', 'SCARA5', 'THNSL2', 'KIAA2012', 'ANKUB1', 'PRKCB', 'CBLN4', 'RSPO2', 'CCDC39', 'SLC12A1', 'NELL2', 'TMPRSS3', 'PENK', 'C14orf180', 'XK', 'TRIM54', 'FAM179A', 'C5orf49', 'ATP2C2', 'ANKRD66', 'TTC29', 'ZMAT4', 'CASQ2', 'DNAI2', 'MRAP2', 'LAMP5', 'CCDC108', 'AK7', 'RGS22', 'ST6GALNAC5', 'PTPN20A', 'GPC5', 'C11orf88', 'RSPH9', 'AGBL4', 'UNC5D', 'OPRK1', 'GMNC', 'IL5RA', 'NNAT', 'PTPN3', 'DNAH2', 'GPR144', 'GPR68', 'LYPD6B', 'FAM216B', 'ERICH3', 'CFAP74', 'DNAH3', 'CAMK4', 'LRRC10B', 'C1orf87', 'CAPSL', 'RGS4', 'MAPK15', 'LRRIQ1', 'PRPH2', 'OGDHL', 'WFDC1', 'VWA5B1', 'PTH2R', 'COX7A1', 'KCNJ6', 'NGEF', 'SLC39A12', 'FAM189A1', 'FAM81B', 'SLC9A2', 'TENM2', 'SLC7A10', 'SLC13A5', 'C9orf24', 'GAS2L2'], '20': ['ZNF215', 'PLA2G7', 'ADIRF', 'NHLRC1', 'SELENBP1', 'CCDC158', 'APLNR', 'KBTBD12', 'CYB5R2', 'C2orf40', 'CH25H', 'ACADL', 'MALRD1', 'RASGEF1A', 'CCL28', 'STEAP1B', 'METTL24', 'RNF128', 'CCNA1', 'IQCA1', 'C16orf89', 'SLC7A2', 'P2RY2', 'BHMT2', 'HAS1', 'FLT3', 'SULT1C2', 'CPAMD8', 'ME1', 'TDRD9', 'PKD2L1', 'TACR2', 'TNFSF9', 'CPXM2', 'APOB'], '21': ['CLEC5A', 'LOX', 'ITIH3', 'CA12', 'CHRDL2', 'VEGFA', 'ENTHD1', 'KISS1R', 'ANGPTL4', 'PNLIPRP3', 'HMOX1', 'MT1G', 'DMBX1', 'SLAMF9', 'CA9', 'ADM', 'MMP8', 'IL36B', 'NPC1L1', 'KRT75', 'SPINK1', 'STC2', 'NDRG1', 'GPRC5A', 'AGXT', 'HILPDA', 'SPAG4', 'LEP', 'MT1H'], '22': ['AIRE', 'NR1H4', 'KLF1', 'LMX1A', 'HOXA11', 'OVOL1', 'DLX2', 'FEV', 'TBX21', 'FOXN4', 'MYOG', 'TLX2', 'RAX', 'RORC', 'NEUROD1', 'PAX7', 'PAX9', 'NR2E3', 'PITX1', 'HOXC13', 'NKX2-2', 'IRX4', 'PAWR', 'ZFP42', 'TCF21', 'NKX6-3', 'MAFA', 'GATA6', 'HNF4G', 'MEIS2', 'PAX5', 'HOXB13', 'TBX15', 'NFE2', 'KLF17', 'NPAS4', 'IRX1', 'NHLH2', 'POU4F3', 'IKZF3', 'GRHL2', 'NR5A1', 'ZIC2', 'ASCL1', 'NKX2-5', 'HOXB7', 'FOXL2'], '23': ['ANKRD22', 'GLDN', 'CALCR', 'CD69', 'HLA-DQB1', 'ACSM5', 'FCRL5', 'IGJ', 'OLR1', 'EMR1', 'GPR55', 'CX3CR1', 'GPR82', 'TMEM119', 'AIM1', 'APOC2', 'PRR15', 'PADI2', 'TNFRSF8', 'GPR141', 'STON1-GTF2A1L', 'P2RY12', 'GAPT', 'PTCRA', 'SIGLEC8', 'DUSP27', 'HLA-DRB5', 'GYPE', 'APOC4-APOC2', 'IL21R', 'HAMP', 'PROX2', 'MS4A4E', 'CLEC12A', 'MORC1', 'CLEC17A', 'C2orf91', 'CLECL1', 'FGF20', 'CTSW', 'HLA-DQA1', 'IGLL5', 'ITK', 'SCIN'], '24': ['PROK2', 'FCN1', 'STEAP4', 'GPR97', 'PPBP', 'KCNJ15', 'APOBEC3A', 'IL1RL1', 'PF4', 'VNN3', 'IL18RAP', 'PHOSPHO1', 'CXCR1', 'CEACAM4', 'TUBB1', 'PADI4', 'FCGR3B', 'CEACAM3', 'S100A12', 'EMR3', 'IL1R2', 'CEACAM8', 'FFAR2', 'ORM1'], '25': ['ZNF732', 'PMAIP1', 'PTGFR', 'TNK1', 'LGALS12', 'FBLN1', 'RIBC2', 'EPHA3', 'RAB17', 'TMEM200A', 'XKRX', 'TDO2', 'KRT17', 'MCOLN2', 'HGF', 'GABRE', 'FGF7', 'SMPDL3B', 'F2RL1', 'SEMA3C', 'FST', 'GSDMC', 'MME', 'ADM2', 'PPL', 'NTRK1', 'ADAMTSL1', 'KCTD19', 'ABI3BP', 'SELL', 'MOCOS', 'ACSM3', 'BAIAP2L1', 'ITGA2', 'KLRC1', 'MFAP5', 'PLEKHG4', 'COLEC12', 'BTBD11', 'CHIT1', 'CDC42BPG', 'FMO3', 'CLMP', 'HTR1D', 'SDK1', 'OSR1', 'F5', 'SULF1', 'C9', 'TPBG', 'PLEKHS1', 'ST6GALNAC2', 'LRIG3', 'MTL5', 'GPR39', 'MCOLN3', 'GPC3', 'SLC27A6', 'LPIN3', 'ADAMTS15', 'CLDN4', 'KCNG1', 'COL17A1', 'LAMC2', 'FAT2', 'ADAMTS12', 'PLEKHG4B', 'TNFRSF18', 'INSRR', 'TRABD2B'], '26': ['CA8', 'KCNH7', 'ASXL3', 'SATL1', 'MYH7', 'KCNT2', 'RHBDL3', 'FXYD2', 'FERMT1', 'CXXC4', 'PRRT4', 'MYO16', 'EPHB1', 'VIPR2', 'SLC17A8', 'GADD45G', 'KCNK2', 'GPR88', 'PROM1', 'CHST9', 'NOL4', 'USP43', 'IGSF9', 'DLL1', 'BEST3', 'OTOG', 'CCDC178', 'RP11-407P15.2', 'MSTN', 'TSHR', 'AKNAD1'], '27': ['SALL4', 'GCM1', 'LHX8', 'TBR1', 'ZFPM2', 'TLX1', 'TLX3', 'NHLH1', 'STOX1', 'LMX1B', 'GATA3', 'HOXB4', 'OLIG1', 'HES6', 'LHX1', 'MEOX1', 'VSX2', 'HOXA2', 'ZNF804A', 'FEZF2'], '28': ['TBX20', 'SOX11', 'SRY', 'BHLHA15', 'RXRG', 'SIM2', 'FOXA3', 'GATA1', 'FOXH1', 'HAND1', 'FOXI1', 'PAX2', 'IRF4', 'PRDM16', 'NEUROG1', 'DLX4', 'FOXF1', 'KCNIP3', 'NFE2L3', 'PITX2', 'FEZF1', 'HES5', 'CTCFL', 'OLIG2', 'POU4F1', 'FOXQ1', 'KLF14', 'PDX1', 'HIF3A', 'HOXA13', 'MSC', 'NEUROD2', 'FOXJ1', 'GLI1', 'TBPL2', 'SPIB', 'EOMES', 'POU4F2', 'INSM1', 'GATA4'], '29': ['SERPINI2', 'TCF24', 'PRSS55', 'OLFM4', 'GHRHR', 'PCDHB1', 'BCO1', 'POU5F1B', 'KCNE2', 'HSPC047', 'CYP3A43', 'COL28A1', 'NTN5', 'UBQLN3', 'SNX31', 'KRTAP5-9', 'CCDC175', 'C10orf62', 'CRYBB3', 'CYP4F12', 'ADIG'], '30': ['NRSN1', 'ATP2B2', 'OPRD1', 'CDH7', 'COCH', 'TSPAN18', 'KCNC1', 'CLSTN2', 'LNX1', 'HRK', 'ABCC8', 'DDX25', 'GABRQ', 'C1orf95', 'KCNA5', 'SPRN', 'FBLL1', 'ADCY1', 'PNMA6A', 'CACNA1G', 'PCP4', 'CENPV', 'KCNK9', 'AGAP2', 'B4GALNT1', 'GLRA2', 'PLD5', 'VWC2L', 'DISP2', 'CHRDL1', 'TMEFF1', 'EEF1A2', 'L1CAM', 'RAB3B', 'CGREF1', 'EFCAB5', 'RIT2', 'WNK2', 'SOX1', 'DAB1', 'AP006285.2', 'ANKRD55', 'FXYD7', 'VSTM5', 'LRRN2', 'KY', 'KCNK10', 'RGS7BP', 'C9orf129', 'FGF17', 'GPR179', 'PTPRT', 'KCNA3', 'MMP24', 'CLVS1', 'SHISA9', 'SEZ6', 'CDK5R2', 'LEMD1', 'CACNA2D2', 'KCNIP4', 'CRHR1', 'WFIKKN2'], '31': ['MYF6', 'SOX10', 'PAX1', 'PEG3', 'HOXA10', 'NANOG', 'MNX1', 'EHF', 'AEBP1', 'HOXB9', 'DLX1', 'FOXP2', 'MYOCD', 'MYRF', 'TCF23', 'SALL3', 'CREB3L1', 'HOXA5', 'ETV4', 'HOXD8', 'MESP2', 'TWIST1'], '32': ['DMRT1', 'EN1', 'PHOX2A', 'TBX1', 'CREB3L3', 'LHX4', 'NKX6-1', 'HNF4A', 'TFAP2D', 'TFAP2C', 'HOXB1', 'HOPX', 'GATA5', 'TCF15', 'LHX3', 'HAND2', 'NKX2-1', 'EMX2', 'OTX2'], '33': ['IFI6', 'IFI44L', 'ZBP1', 'BA

In [24]:
# How many unique metabolites in module2mets.values()?
module2mets_values = [item for sublist in module2mets.values() for item in sublist]
print(f'There are {len(set(module2mets_values))} unique metabolites in module2mets')

There are 53 unique metabolites in module2mets

# Subset metabolite-gene interactions file for metabolites that are in the dataset

In [25]:
interactions = pd.read_csv(metabolite_interactions_file, sep='\t')
interactions

/tmp/ipykernel_78145/3026841620.py:1: DtypeWarning: Columns (15,16,17,18,19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  interactions = pd.read_csv(metabolite_interactions_file, sep='\t')

,Name,HMDB,ChEBI,KEGG,PubChem,IUPAC_Name,SMILES,InChIKey,PDB_ID,Kingdom,...,IntAct,UniProtKB,chEMBL,LINCS,STITCH,BioGRID,Human1_GEM_dist1,Human1_GEM_dist2,MetalinksDB,All_database_interactions
0,1-Methylhistidine,HMDB0000001,50599.0,C01152,92105.0,(2S)-2-amino-3-(1-methyl-1H-imidazol-4-yl)prop...,CN1C=NC(C[C@H](N)C(O)=O)=C1,BRMWTNUJHUMWMS-LURJTMIESA-N,NaN,Organic acids and derivatives,...,none,none,none,NaN,NaN,ACTA1,NaN,NaN,NaN,ACTA1
1,"1,3-Diaminopropane",HMDB0000002,15725.0,C00986,428.0,"propane-1,3-diamine",NCCCN,XFNJVJPLKCPIBV-UHFFFAOYSA-N,NaN,Organic nitrogen compounds,...,none,DHPS|DS|DHPS|DHPS|DHPS|DHPS|DHPS|DHPS,none,NaN,NaN,NaN,AOC1|AOC2|AOC3|DHPS|SLC22A1|SLC22A2|SLC22A3,AADAC|AASDH|ABHD12|ABHD6|ACAA1|ACAA2|ACE|ACE2|...,NaN,DHPS|DS|DHPS|DHPS|DHPS|DHPS|DHPS|DHPS|AOC1|AOC...
2,2-Ketobutyric acid,HMDB0000005,30831.0,C00109,58.0,2-oxobutanoic acid,CCC(=O)C(O)=O,TYEYBOSBBBHJIV-UHFFFAOYSA-N,NaN,Organic acids and derivatives,...,none,RIDA|HRSP12|SDS|SDH|SDSL|GOT1|CTH|AGXT2|AGT2|A...,none,NaN,NaN,NaN,BCKDHA|BCKDHB|CTH|GPT|LDHAL6A|LDHAL6B|LDHB|LDH...,AADAC|AADAT|ABAT|ABHD12|ABHD6|ACE|ACE2|ACHE|AC...,NaN,RIDA|HRSP12|SDS|SDH|SDSL|GOT1|CTH|AGXT2|AGT2|A...
3,2-Hydroxybutyric acid,HMDB0000008,50613.0,C05984,440864.0,(2S)-2-hydroxybutanoic acid,CC[C@H](O)C(O)=O,AFENDNXGAFYKQO-VKHMYHEASA-N,NaN,Organic acids and derivatives,...,none,none,none,NaN,NaN,NaN,NaN,NaN,SLC16A6|LDHC|SLC16A3|LDHB|LDHAL6B|SLC16A7|SLC1...,SLC16A6|LDHC|SLC16A3|LDHB|LDHAL6B|SLC16A7|SLC1...
4,2-Methoxyestrone,HMDB0000010,1189.0,C05299,440624.0,"(1S,10R,11S,15S)-5-hydroxy-4-methoxy-15-methyl...",[H][C@@]12CCC(=O)[C@@]1(C)CC[C@]1([H])C3=C(CC[...,WHEUWNKSCXYKBU-QPWUGHHJSA-N,NaN,Lipids and lipid-like molecules,...,none,COMT|UGT1A8|GNT1|UGT1|COMT|COMT|COMT|COMT|COMT,none,HSD17B1,NaN,NaN,ABCB1|COMT|LRTOMT,AADAC|ABCB1|ABHD12|ABHD6|ACE|ACE2|ACHE|ACP2|AC...,UGT1A8|ABCB1|COMT,COMT|UGT1A8|GNT1|UGT1|COMT|COMT|COMT|COMT|COMT...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217915,Nordeoxycholic acid,HMDB0304947,NaN,NaN,314374.0,"3-{5,16-dihydroxy-2,15-dimethyltetracyclo[8.7....",CC(CC(O)=O)C1CCC2C3CCC4CC(O)CCC4(C)C3CC(O)C12C,PLRQOCVIINWCFA-UHFFFAOYSA-N,NaN,Lipids and lipid-like molecules,...,none,none,none,NaN,NaN,NaN,NaN,NaN,NaN,NaN
217916,3-Oxo-5beta-cholanoic acid,HMDB0304950,NaN,NaN,543448.0,"4-{2,15-dimethyl-5-oxotetracyclo[8.7.0.0^{2,7}...",CC(CCC(O)=O)C1CCC2C3CCC4CC(=O)CCC4(C)C3CCC12C,KIQFUORWRVZTHT-UHFFFAOYSA-N,NaN,Lipids and lipid-like molecules,...,none,DHRS4|SDR25C2|UNQ851/PRO1800,none,NaN,NaN,NaN,NaN,NaN,NaN,DHRS4|SDR25C2|UNQ851/PRO1800
217917,Glycerol 1-myristate,HMDB0304951,75562.0,NaN,79050.0,"2,3-dihydroxypropyl tetradecanoate",CCCCCCCCCCCCCC(=O)OCC(O)CO,DCBSHORRWZKAKO-UHFFFAOYSA-N,NaN,Lipids and lipid-like molecules,...,none,ENPP6|UNQ1889/PRO4334|EPHX2|ABHD6|MGLL|MOGAT1|...,none,NaN,NaN,NaN,NaN,NaN,NaN,ENPP6|UNQ1889/PRO4334|EPHX2|ABHD6|MGLL|MOGAT1|...
217918,O-Phenolsulfonic acid,HMDB0304953,71049.0,NaN,11867.0,2-hydroxybenzene-1-sulfonic acid,OC1=CC=CC=C1S(O)(=O)=O,IULJSGIJJZZUMF-UHFFFAOYSA-N,NaN,Benzenoids,...,none,none,none,NaN,NaN,NaN,NaN,NaN,NaN,NaN
217919,d-Fucitol,HMDB0304954,NaN,NaN,445724.0,"(2R,3S,4R,5S)-hexane-1,2,3,4,5-pentol",[H][C@@](C)(O)[C@@]([H])(O)[C@@]([H])(O)[C@]([...,SKCKOFZKJLZSFA-KCDKBNATSA-N,NaN,Organic oxygen compounds,...,none,none,none,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
# contextualize metabolite-gene interactions to dataset
metabolite_mapping = pd.read_csv(annotated_mets, sep=',')
print(metabolite_mapping)
# Create a dictionary that maps Query to HMDB
metabolite_mapping = metabolite_mapping.set_index('Query')['HMDB'].dropna().to_dict()
print(metabolite_mapping)
metabolites_hmdb = metabolite_mapping.values()
print(f'{len(metabolites_hmdb)} metabolites in this dataset are mapped to a hmdb id')

                      Query                   Match         HMDB   PubChem  \
0     2_hydroxybutyric_acid   2-Hydroxybutyric acid  HMDB0000008  440864.0
1    2_hydroxyglutaric_acid      2-Hydroxyglutarate  HMDB0059655      43.0
2     3_hydroxybutyric_acid   3-Hydroxybutyric acid  HMDB0000011     441.0
3        3_phosphoglycerate  3-Phosphoglyceric acid  HMDB0000807     724.0
4                   adenine                 Adenine  HMDB0000034     190.0
..                      ...                     ...          ...       ...
129             Unknown_047                     NaN          NaN       NaN
130             Unknown_048                     NaN          NaN       NaN
131             Unknown_049                     NaN          NaN       NaN
132             Unknown_050                     NaN          NaN       NaN
133             Unknown_051                     NaN          NaN       NaN

       ChEBI    KEGG  METLIN                 SMILES  Comment
0    50613.0  C05984  3783.0       CC[C@H](O)C(O)=O        1
1    17084.0  C02630     NaN     OC(CCC(O)=O)C(O)=O        1
2    17066.0  C01089     NaN      C[C@@H](O)CC(O)=O        1
3    17050.0  C00597   150.0  OC(COP(O)(O)=O)C(O)=O        1
4    16708.0  C00147    85.0     NC1=C2NC=NC2=NC=N1        1
..       ...     ...     ...                    ...      ...
129      NaN     NaN     NaN                    NaN        0
130      NaN     NaN     NaN                    NaN        0
131      NaN     NaN     NaN                    NaN        0
132      NaN     NaN     NaN                    NaN        0
133      NaN     NaN     NaN                    NaN        0

[134 rows x 9 columns]
{'2_hydroxybutyric_acid': 'HMDB0000008', '2_hydroxyglutaric_acid': 'HMDB0059655', '3_hydroxybutyric_acid': 'HMDB0000011', '3_phosphoglycerate': 'HMDB0000807', 'adenine': 'HMDB0000034', 'aminomalonic_acid_(spectralmatch)': 'HMDB0001147', 'campesterol': 'HMDB0002869', 'capricacid': 'HMDB0000511', 'cholesterol_(spectral_match)': 'HMDB0000067', 'citricacid': 'HMDB0000094', 'creatinine': 'HMDB0000562', 'D_(_)_galactose': 'HMDB0000143', 'dehydroascorbic_acid': 'HMDB0001264', 'D_fructose_6_phosphate': 'HMDB0304311', 'D_gluconic_acid': 'HMDB0000625', 'D_glucose': 'HMDB0000122', 'D_glucose_6_phosphate': 'HMDB0001401', 'DL_isoleucine': 'HMDB0000172', 'D_malic_acid': 'HMDB0031518', 'D_mannitol': 'HMDB0000765', 'D_mannose': 'HMDB0000169', 'docosahexaenoic_acid': 'HMDB0002183', 'D_sorbitol': 'HMDB0000247', 'fructose': 'HMDB0000660', 'fumaric_acid': 'HMDB0000134', 'galactitol': 'HMDB0000107', 'glyceric_acid': 'HMDB0000139', 'glycerol_3_phosphate': 'HMDB0000126', 'glycine': 'HMDB0000123', 'glycolic_acid': 'HMDB0000115', 'heptadecanoic_acid': 'HMDB0002259', 'homocysteine': 'HMDB0000742', 'hypotaurine': 'HMDB0000965', 'L_2_aminoadipic_acid': 'HMDB0000510', 'lactic_acid': 'HMDB0000190', 'L_aspartic_acid': 'HMDB0000191', 'L_cysteine': 'HMDB0000192', 'L_glutamic_acid': 'HMDB0000148', 'L_glutamine': 'HMDB0000641', 'linoleic_acid': 'HMDB0000673', 'L_leucine': 'HMDB0000687', 'L_lysine': 'HMDB0000182', 'L_methionine': 'HMDB0000696', 'L_mimosine': 'HMDB0015188', 'L_proline': 'HMDB0000162', 'L_pyroglutamic_acid': 'HMDB0000267', 'L_serine': 'HMDB0000187', 'L_threonine': 'HMDB0000167', 'L_tyrosine': 'HMDB0000158', 'L_valine': 'HMDB0000883', 'maltose': 'HMDB0000163', 'myo_inositol': 'HMDB0000211', 'myristic_acid': 'HMDB0000806', 'N_formylglycine': 'HMDB0255145', 'N_methylalanine': 'HMDB0094692', 'oleic_acid': 'HMDB0000207', 'palmitic_acid': 'HMDB0000220', 'pantothenic_acid': 'HMDB0000210', 'phenylalanine': 'HMDB0000159', 'phosphoenolpyruvic_acid': 'HMDB0000263', 'porphine': 'HMDB0000839', 'propylene_glycol': 'HMDB0001881', 'putrescine': 'HMDB0001414', 'pyrophosphate': 'HMDB0000250', 'pyruvic_acid': 'HMDB0000243', 'sarcosine': 'HMDB0000271', 'scyllo_inositol': 'HMDB0006088', 'stearic_acid': 'HMDB0000827', 'sucrose': 'HMDB0000258', 'timonacic': 'HMDB0258979', 'uracil': 'HMDB0000300', 'urea': 'HMDB0000294', "uridine_5'_monophosphate": 'HMDB0000288', 'xylitol': 'HMDB0242149'}
74 metabolites in this dataset are mapped to a hmdb id

In [27]:
# How many metabolites_hmdb are in the interactions file?
metabolites_in_interactions = interactions['HMDB'].isin(metabolites_hmdb)
print(f'{metabolites_in_interactions.sum()} metabolites in the interactions file are in the dataset')
# how many metabolites in the dataset are in the interactions file?
metabolites_in_dataset = pd.Series(list(metabolites_hmdb)).isin(interactions['HMDB'])
print(f'{metabolites_in_dataset.sum()} metabolites in the dataset are in the interactions file')

74 metabolites in the interactions file are in the dataset
74 metabolites in the dataset are in the interactions file

# Plot shortest paths between metabolite regulators and module genes in the LemonIte PKN

In [28]:
# Read networks
PKN = pd.read_csv(PKNnetwork_file, sep='\t', header=0)
# split Node1 on '_' and keep the last part
PKN['Node1'] = PKN['Node1'].str.split('_').str[-1]
print(PKN)

lemonnetwork = pd.read_csv(lemonnetwork_file, sep='\t', header=0)
print(lemonnetwork)
# Extract nodes from both networks
lemonnetwork_nodes = list(set(lemonnetwork['Regulator'].tolist() + lemonnetwork['Target'].tolist()))
PKN_nodes = list(set(PKN['Node1'].tolist() + PKN['Node2'].tolist()))

# create name_to_hmdb mapping for metabolites
name_to_hmdb = pd.read_csv(annotated_mets, sep=',')
name_to_hmdb = name_to_hmdb.set_index('Query')['HMDB'].dropna().to_dict()
print(name_to_hmdb)

               Node1     Node2     Source             Type
0            CYP26B1   ALDH1A2     STRING              PPI
1            CYP26B1   ALDH1A3     STRING              PPI
2            CYP26B1   ALDH1A1     STRING              PPI
3            CYP26B1    CRABP1     STRING              PPI
4            CYP26B1    CYP2B6     STRING              PPI
...              ...       ...        ...              ...
2558076  HMDB0304951    MOGAT2  UniProtKB  metabolite-gene
2558077  HMDB0304951       DC5  UniProtKB  metabolite-gene
2558078  HMDB0304951   DGAT2L5  UniProtKB  metabolite-gene
2558079  HMDB0304951    ABHD12  UniProtKB  metabolite-gene
2558080  HMDB0304951  C20orf22  UniProtKB  metabolite-gene

[2558081 rows x 4 columns]
             Regulator  Target      Score  Lemon_module        Type
0                 EMX1  VSTM2L  70.187232             0     TF-gene
1                 EMX1  GABRA5  70.187232             0     TF-gene
2                 EMX1    SYT4  70.187232             0     TF-gene
3                 EMX1   CREG2  70.187232             0     TF-gene
4                 EMX1  SYNGR3  70.187232             0     TF-gene
...                ...     ...        ...           ...         ...
27848  PE(P_16_0/22_4)   NXPH3   4.758874            62  Lipid-gene
27849  PE(P_16_0/22_4)  COL9A1   4.758874            62  Lipid-gene
27850  PE(P_16_0/22_4)    GAD1   4.758874            62  Lipid-gene
27851  PE(P_16_0/22_4)  FRMPD1   4.758874            62  Lipid-gene
27852  PE(P_16_0/22_4)  SMIM18   4.758874            62  Lipid-gene

[27853 rows x 5 columns]
{'2_hydroxybutyric_acid': 'HMDB0000008', '2_hydroxyglutaric_acid': 'HMDB0059655', '3_hydroxybutyric_acid': 'HMDB0000011', '3_phosphoglycerate': 'HMDB0000807', 'adenine': 'HMDB0000034', 'aminomalonic_acid_(spectralmatch)': 'HMDB0001147', 'campesterol': 'HMDB0002869', 'capricacid': 'HMDB0000511', 'cholesterol_(spectral_match)': 'HMDB0000067', 'citricacid': 'HMDB0000094', 'creatinine': 'HMDB0000562', 'D_(_)_galactose': 'HMDB0000143', 'dehydroascorbic_acid': 'HMDB0001264', 'D_fructose_6_phosphate': 'HMDB0304311', 'D_gluconic_acid': 'HMDB0000625', 'D_glucose': 'HMDB0000122', 'D_glucose_6_phosphate': 'HMDB0001401', 'DL_isoleucine': 'HMDB0000172', 'D_malic_acid': 'HMDB0031518', 'D_mannitol': 'HMDB0000765', 'D_mannose': 'HMDB0000169', 'docosahexaenoic_acid': 'HMDB0002183', 'D_sorbitol': 'HMDB0000247', 'fructose': 'HMDB0000660', 'fumaric_acid': 'HMDB0000134', 'galactitol': 'HMDB0000107', 'glyceric_acid': 'HMDB0000139', 'glycerol_3_phosphate': 'HMDB0000126', 'glycine': 'HMDB0000123', 'glycolic_acid': 'HMDB0000115', 'heptadecanoic_acid': 'HMDB0002259', 'homocysteine': 'HMDB0000742', 'hypotaurine': 'HMDB0000965', 'L_2_aminoadipic_acid': 'HMDB0000510', 'lactic_acid': 'HMDB0000190', 'L_aspartic_acid': 'HMDB0000191', 'L_cysteine': 'HMDB0000192', 'L_glutamic_acid': 'HMDB0000148', 'L_glutamine': 'HMDB0000641', 'linoleic_acid': 'HMDB0000673', 'L_leucine': 'HMDB0000687', 'L_lysine': 'HMDB0000182', 'L_methionine': 'HMDB0000696', 'L_mimosine': 'HMDB0015188', 'L_proline': 'HMDB0000162', 'L_pyroglutamic_acid': 'HMDB0000267', 'L_serine': 'HMDB0000187', 'L_threonine': 'HMDB0000167', 'L_tyrosine': 'HMDB0000158', 'L_valine': 'HMDB0000883', 'maltose': 'HMDB0000163', 'myo_inositol': 'HMDB0000211', 'myristic_acid': 'HMDB0000806', 'N_formylglycine': 'HMDB0255145', 'N_methylalanine': 'HMDB0094692', 'oleic_acid': 'HMDB0000207', 'palmitic_acid': 'HMDB0000220', 'pantothenic_acid': 'HMDB0000210', 'phenylalanine': 'HMDB0000159', 'phosphoenolpyruvic_acid': 'HMDB0000263', 'porphine': 'HMDB0000839', 'propylene_glycol': 'HMDB0001881', 'putrescine': 'HMDB0001414', 'pyrophosphate': 'HMDB0000250', 'pyruvic_acid': 'HMDB0000243', 'sarcosine': 'HMDB0000271', 'scyllo_inositol': 'HMDB0006088', 'stearic_acid': 'HMDB0000827', 'sucrose': 'HMDB0000258', 'timonacic': 'HMDB0258979', 'uracil': 'HMDB0000300', 'urea': 'HMDB0000294', "uridine_5'_monophosphate": 'HMDB0000288', 'xylitol': 'HMDB0242149'}

In [29]:
# get unique values from Type column
types = PKN['Source'].unique()
print(types)

['STRING' 'BioGRID_genes' 'HuRI' 'BioGRID' 'UniProtKB' 'Human1_GEM_dist1'
 'Human1_GEM_dist2' 'MetalinksDB' 'LINCS' 'chEMBL' 'IntAct' 'STITCH']

In [30]:
# Map metabolite names in 'Regulator' column to HMDB ids
lemonnetwork['Regulator'] = lemonnetwork['Regulator'].map(name_to_hmdb) # Only rows involving a metabolite as regulator will be mapped, other will be set to nan
# drop rows with nan values in 'Regulator' column
lemonnetwork = lemonnetwork.dropna(subset=['Regulator'])
print(lemonnetwork)

         Regulator  Target      Score  Lemon_module             Type
9969   HMDB0000562  VSTM2L  64.743192             0  Metabolite-gene
9970   HMDB0000562  GABRA5  64.743192             0  Metabolite-gene
9971   HMDB0000562    SYT4  64.743192             0  Metabolite-gene
9972   HMDB0000562   CREG2  64.743192             0  Metabolite-gene
9973   HMDB0000562  SYNGR3  64.743192             0  Metabolite-gene
...            ...     ...        ...           ...              ...
14982  HMDB0000192   NXPH3  13.740352            62  Metabolite-gene
14983  HMDB0000192  COL9A1  13.740352            62  Metabolite-gene
14984  HMDB0000192    GAD1  13.740352            62  Metabolite-gene
14985  HMDB0000192  FRMPD1  13.740352            62  Metabolite-gene
14986  HMDB0000192  SMIM18  13.740352            62  Metabolite-gene

[4183 rows x 5 columns]

In [31]:
# remove nodes from lemonnetwork that are not in the PKN
lemonnetwork = lemonnetwork[lemonnetwork['Regulator'].isin(PKN_nodes) & lemonnetwork['Target'].isin(PKN_nodes)]
lemonnetwork
# how many Metabolite-gene interactions remain in lemonnetwork?
#lemonnetwork_metabolites = lemonnetwork[lemonnetwork['Type'] == 'Metabolite-gene']
print(f'The LemonIte network contains {lemonnetwork_metabolites.shape[0]} Metabolite-gene interactions')

The LemonIte network contains 5018 Metabolite-gene interactions

In [32]:
PKN.nx = nx.from_pandas_edgelist(PKN, 'Node1', 'Node2')
# How many nodes and edges does the PKN contain?
print(f'The PKN contains {PKN.nx.number_of_nodes()} nodes and {PKN.nx.number_of_edges()} edges')
lemonnetwork.nx = nx.from_pandas_edgelist(lemonnetwork, 'Regulator', 'Target')
# How many nodes and edges does the LemonIte network contain?
print(f'The LemonIte network contains {lemonnetwork.nx.number_of_nodes()} nodes and {lemonnetwork.nx.number_of_edges()} edges')

The PKN contains 41137 nodes and 1955213 edges
The LemonIte network contains 1821 nodes and 3975 edges

/tmp/ipykernel_78145/162738182.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  PKN.nx = nx.from_pandas_edgelist(PKN, 'Node1', 'Node2')
/tmp/ipykernel_78145/162738182.py:4: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  lemonnetwork.nx = nx.from_pandas_edgelist(lemonnetwork, 'Regulator', 'Target')

In [33]:
lemonnetwork

         Regulator   Target      Score  Lemon_module             Type
9969   HMDB0000562   VSTM2L  64.743192             0  Metabolite-gene
9970   HMDB0000562   GABRA5  64.743192             0  Metabolite-gene
9971   HMDB0000562     SYT4  64.743192             0  Metabolite-gene
9972   HMDB0000562    CREG2  64.743192             0  Metabolite-gene
9973   HMDB0000562   SYNGR3  64.743192             0  Metabolite-gene
...            ...      ...        ...           ...              ...
14981  HMDB0000192  TSPAN11  13.740352            62  Metabolite-gene
14982  HMDB0000192    NXPH3  13.740352            62  Metabolite-gene
14983  HMDB0000192   COL9A1  13.740352            62  Metabolite-gene
14984  HMDB0000192     GAD1  13.740352            62  Metabolite-gene
14985  HMDB0000192   FRMPD1  13.740352            62  Metabolite-gene

[3975 rows x 5 columns]

# Plot some shortest paths and their neighborhoods

In [34]:
def create_edge_legend_by_category(ax, edge_styles, edge_info):
    """Create a legend showing edge categories present in the network"""
    from matplotlib.lines import Line2D
    from matplotlib.patches import FancyArrowPatch
    
    # Get unique categories in this network
    present_categories = set()
    for info in edge_info.values():
        present_categories.add(info.get('category', 'Unknown'))
    
    # Create legend elements for all categories in edge_styles
    legend_elements = []
    for category in sorted(edge_styles.keys()):
        style = edge_styles[category]
        
        if category == 'Metabolic_pathway':
            # For Metabolic_pathway, show a line with a dot marker at the end
            legend_elements.append(
                Line2D([0, 1], [0, 0], 
                      marker='o', markersize=6, markerfacecolor=style['color'],
                      markeredgecolor='black', markeredgewidth=0.5,
                      color=style['color'], linewidth=style['width'],
                      linestyle=style['style'], alpha=style['alpha'],
                      label=style['label'])
            )
        elif category == 'Causal':
            # Arrow marker for Causal - use FancyArrowPatch to match drawing
            legend_elements.append(
                FancyArrowPatch((0, 0), (1, 0),
                              arrowstyle='-|>',
                              mutation_scale=15,
                              color=style['color'],
                              linewidth=style['width'],
                              alpha=style['alpha'],
                              label=style['label'])
            )
        else:
            # Normal line for others (PPI, Ambiguous, Unknown)
            legend_elements.append(
                Line2D([0, 1], [0, 0], 
                      color=style['color'], 
                      linewidth=style['width'],
                      linestyle=style['style'],
                      alpha=style['alpha'],
                      label=style['label'])
            )
    
    # Add legend if there are elements
    if legend_elements:
        return legend_elements
    return []

In [35]:
########################################################################################################################################
# Helper functions for categorizing and styling edges based on interaction type and source
########################################################################################################################################

def get_edge_type_category(source, edge_type):
    """
    Categorize edge sources into interaction types based on the edge type (metabolite-gene or PPI)
    
    Parameters:
    -----------
    source : str
        The source database (e.g., 'LINCS', 'STRING', 'BioGRID')
    edge_type : str
        Type of edge - either 'metabolite-gene' or 'PPI'
    
    Returns:
    --------
    str : Interaction category
    """
    
    if edge_type == 'metabolite-gene':
        # Categorization for metabolite-gene interactions only
        causal_sources = ['LINCS', 'chEMBL']
        metabolic_sources = ['Human1_GEM_dist1', 'Human1_GEM_dist2']
        
        if source in causal_sources:
            return 'Causal'
        elif source in metabolic_sources:
            return 'Metabolic_pathway'
        else:
            return 'Ambiguous'
    
    elif edge_type == 'PPI':
        # All PPI interactions are simply categorized as PPI (shown as gray)
        return 'PPI'
    
    else:
        return 'PPI'


def get_edge_style_mapping():
    """
    Define visual styles for each interaction category
    Metabolite-gene interactions have 3 types (Causal, Metabolic_pathway, Ambiguous)
    PPI interactions are all shown as gray lines
    """
    return {
        # Metabolite-gene interaction styles - all dark grey, distinguished by markers
        'Causal': {
            'color': '#555555',  # Dark grey - causal relationships
            'style': 'solid',
            'width': 3.0,
            'alpha': 0.9,
            'label': 'Causal (LINCS/chEMBL)'
        },
        'Metabolic_pathway': {
            'color': '#555555',  # Dark grey - metabolic pathways
            'style': 'solid',
            'width': 2.5,
            'alpha': 0.85,
            'label': 'Metabolic pathway (GEM)'
        },
        'Ambiguous': {
            'color': '#555555',  # Dark grey - ambiguous
            'style': 'solid',
            'width': 2.0,
            'alpha': 0.7,
            'label': 'Ambiguous (other)'
        },
        
        # PPI interaction style (light grey)
        'PPI': {
            'color': '#A9A9A9',  # Darker light grey - protein-protein interactions
            'style': 'solid',
            'width': 1.5,
            'alpha': 0.5,
            'label': 'PPI'
        }
    }


def get_edge_source_and_type(PKN_df, node1, node2):
    """
    Get both the source database and the interaction type for an edge
    
    Returns:
    --------
    tuple : (source, edge_type, category)
    """
    # Check both directions (undirected graph)
    match = PKN_df[((PKN_df['Node1'] == node1) & (PKN_df['Node2'] == node2)) |
                   ((PKN_df['Node1'] == node2) & (PKN_df['Node2'] == node1))]
    
    if not match.empty:
        source = match.iloc[0]['Source']
        edge_type = match.iloc[0]['Type']
        category = get_edge_type_category(source, edge_type)
        return source, edge_type, category
    
    return 'unknown', 'unknown', 'PPI'


def create_edge_legend_by_category(ax, edge_styles, edge_info):
    """Create a legend showing edge categories present in the network"""
    from matplotlib.lines import Line2D
    from matplotlib.patches import FancyArrowPatch
    
    # Get unique categories in this network
    present_categories = set()
    for info in edge_info.values():
        present_categories.add(info.get('category', 'PPI'))
    
    # Create legend elements for all categories in edge_styles
    legend_elements = []
    for category in sorted(edge_styles.keys()):
        style = edge_styles[category]
        
        if category == 'Metabolic_pathway':
            # For Metabolic_pathway, show a line with a dot marker at the end
            legend_elements.append(
                Line2D([0, 1], [0, 0], 
                      marker='o', markersize=6, markerfacecolor=style['color'],
                      markeredgecolor='black', markeredgewidth=0.5,
                      color=style['color'], linewidth=style['width'],
                      linestyle=style['style'], alpha=style['alpha'],
                      label=style['label'])
            )
        elif category == 'Causal':
            # For Causal, show a line with an arrow marker
            legend_elements.append(
                Line2D([0, 1], [0, 0], 
                      marker='>', markersize=8, markerfacecolor=style['color'],
                      markeredgecolor='black', markeredgewidth=0.5,
                      color=style['color'], linewidth=style['width'],
                      linestyle=style['style'], alpha=style['alpha'],
                      label=style['label'])
            )
        else:
            # Normal line for others (PPI, Ambiguous)
            legend_elements.append(
                Line2D([0, 1], [0, 0], 
                      color=style['color'], 
                      linewidth=style['width'],
                      linestyle=style['style'],
                      alpha=style['alpha'],
                      label=style['label'])
            )
    
    # Add legend if there are elements
    if legend_elements:
        return legend_elements
    return []


def create_node_legend(ax, has_metabolites, has_tfs, has_targets, has_bridge):
    """Create a legend showing node colors present in the network"""
    from matplotlib.patches import Patch
    
    legend_elements = []
    
    if has_metabolites:
        legend_elements.append(Patch(facecolor='red', edgecolor='black', label='Metabolites'))
    if has_tfs:
        legend_elements.append(Patch(facecolor='lightgreen', edgecolor='black', label='TFs'))
    if has_targets:
        legend_elements.append(Patch(facecolor='orange', edgecolor='black', label='Targets'))
    if has_bridge:
        legend_elements.append(Patch(facecolor='lightgrey', edgecolor='black', label='Bridge'))
    
    # Return legend elements
    return legend_elements


def print_edge_statistics(edge_info):
    """Print statistics about edge types and categories"""
    from collections import Counter
    
    categories = [info.get('category', 'PPI') for info in edge_info.values()]
    types = [info.get('type', 'unknown') for info in edge_info.values()]
    sources = [info.get('source', 'unknown') for info in edge_info.values()]
    
    print("\n=== Edge Statistics ===")
    print("\nBy Category:")
    for cat, count in Counter(categories).most_common():
        print(f"  {cat}: {count}")
    
    print("\nBy Type:")
    for typ, count in Counter(types).most_common():
        print(f"  {typ}: {count}")
    
    print("\nBy Source:")
    for src, count in Counter(sources).most_common():
        print(f"  {src}: {count}")

In [36]:
def export_to_cytoscape_with_categories(graph, module, hmdb_to_name, TF_regulators, target_genes, edge_info, PKN_df):
    """Export network with edge category information for Cytoscape"""
    import os
    
    cytoscape_dir = "./Networks/cytoscape"
    os.makedirs(cytoscape_dir, exist_ok=True)
    
    # Export edges with full information
    edges_data = []
    for u, v in graph.edges():
        node1 = hmdb_to_name.get(u, u)
        node2 = hmdb_to_name.get(v, v)
        
        info = edge_info.get((u, v)) or edge_info.get((v, u), {})
        source = info.get('source', 'unknown')
        edge_type = info.get('type', 'unknown')
        category = info.get('category', 'PPI')
        
        edges_data.append({
            'Node1': node1,
            'Node2': node2,
            'Source': source,
            'Type': edge_type,
            'Category': category
        })
    
    edges_df = pd.DataFrame(edges_data)
    edges_file = f"{cytoscape_dir}/module_{module}_edges_categorized.tsv"
    edges_df.to_csv(edges_file, sep='\t', index=False)
    
    # Export node attributes
    attributes_data = []
    for node in graph.nodes():
        if node in hmdb_to_name:
            node_type = 'metabolite'
            label = hmdb_to_name[node]
        elif node in TF_regulators:
            node_type = 'TF'
            label = node
        elif node in target_genes:
            node_type = 'module_gene'
            label = node
        else:
            node_type = 'bridge_node'
            label = node
        
        attributes_data.append({
            'Node': label,
            'Label': label,
            'Type': node_type
        })
    
    attributes_df = pd.DataFrame(attributes_data)
    attributes_file = f"{cytoscape_dir}/module_{module}_attributes.tsv"
    attributes_df.to_csv(attributes_file, sep='\t', index=False)
    
    print(f"\nCytoscape files with categorized edges saved for module {module}:")
    print(f"  Edges: {edges_file}")
    print(f"  Attributes: {attributes_file}")

In [37]:
def get_edge_style_mapping():
    """
    Define visual styles for each interaction category
    Metabolite-gene interactions have 3 types (Causal, Metabolic_pathway, Ambiguous)
    PPI interactions are all shown as gray lines
    """
    return {
        # Metabolite-gene interaction styles - all dark grey, distinguished by markers
        'Causal': {
            'color': '#555555',  # Dark grey - causal relationships
            'style': 'solid',
            'width': 3.0,
            'alpha': 0.9,
            'label': 'Causal (LINCS/chEMBL)'
        },
        'Metabolic_pathway': {
            'color': '#555555',  # Dark grey - metabolic pathways
            'style': 'solid',
            'width': 2.5,
            'alpha': 0.85,
            'label': 'Metabolic pathway (GEM)'
        },
        'Ambiguous': {
            'color': '#555555',  # Dark grey - ambiguous
            'style': 'solid',
            'width': 2.0,
            'alpha': 0.7,
            'label': 'Ambiguous (other)'
        },
        
        # PPI interaction style (light grey)
        'PPI': {
            'color': '#A9A9A9',  # Darker light grey - protein-protein interactions
            'style': 'solid',
            'width': 1.5,
            'alpha': 0.5,
            'label': 'PPI'
        },
        
        # Unknown/fallback
        'Unknown': {
            'color': '#555555',  # Dark gray
            'style': 'solid',
            'width': 1.0,
            'alpha': 0.4,
            'label': 'Unknown'
        }
    }

In [38]:
import os
import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import FancyArrowPatch
from matplotlib.lines import Line2D
from matplotlib.patches import Patch


def draw_subnetwork(module, target_genes, TF_regulators, metabolite_regulators,
                    PKN_df, PKN_nx, name_to_hmdb):
    """
    Draw subnetwork with clearer arrows, dots, and spacing.
    Uses edge categories and node types for styling.
    """

    # === Setup ===
    hmdb_to_name = {v: k for k, v in name_to_hmdb.items()}
    print(f'Module {module}: {len(metabolite_regulators)} metabolites, '
          f'{len(TF_regulators)} TFs, {len(target_genes)} targets.')

    to_draw = nx.Graph()
    edge_info = {}
    met_regs = []

    # --- STEP 1: Metabolite regulators ---
    for reg in metabolite_regulators:
        if reg not in name_to_hmdb:
            continue
        regulator = name_to_hmdb[reg]
        met_regs.append(regulator)
        if regulator not in PKN_nx:
            continue
        to_draw.add_node(regulator)
        for target in target_genes:
            try:
                if nx.shortest_path_length(PKN_nx, source=regulator, target=target) == 1:
                    to_draw.add_nodes_from([regulator, target])
                    to_draw.add_edge(regulator, target)
                    source, edge_type, category = get_edge_source_and_type(PKN_df, regulator, target)
                    edge_info[(regulator, target)] = {'source': source, 'type': edge_type, 'category': category}
            except (nx.NetworkXNoPath, nx.NodeNotFound):
                continue

    # --- STEP 2: TF regulators (PPI edges) ---
    for TF in TF_regulators:
        for regulator in met_regs:
            try:
                length = nx.shortest_path_length(PKN_nx, source=TF, target=regulator)
                if length <= 2:
                    path = nx.shortest_path(PKN_nx, source=TF, target=regulator)
                    for i in range(len(path) - 1):
                        u, v = path[i], path[i + 1]
                        to_draw.add_edge(u, v)
                        source, edge_type, category = get_edge_source_and_type(PKN_df, u, v)
                        edge_info[(u, v)] = {'source': source, 'type': edge_type, 'category': category}
            except (nx.NetworkXNoPath, nx.NodeNotFound):
                continue

    # --- STEP 3: Add edges among included nodes ---
    subgraph = PKN_nx.subgraph(to_draw.nodes())
    for u, v in subgraph.edges():
        if not to_draw.has_edge(u, v):
            to_draw.add_edge(u, v)
            source, edge_type, category = get_edge_source_and_type(PKN_df, u, v)
            edge_info[(u, v)] = {'source': source, 'type': edge_type, 'category': category}

    to_draw.remove_edges_from(nx.selfloop_edges(to_draw))
    disconnected = [n for n in to_draw if to_draw.degree(n) == 0]
    to_draw.remove_nodes_from(disconnected)

    if not to_draw.nodes:
        print(f"No valid connections for module {module}.")
        return

    # === Layout ===
    pos = nx.spring_layout(to_draw, k=1.8, iterations=200, seed=42)

    # === Node categories ===
    hmdb_nodes = [n for n in to_draw if n in name_to_hmdb.values()]
    tf_nodes = [n for n in to_draw if n in TF_regulators]
    target_nodes = [n for n in to_draw if n in target_genes]
    bridge_nodes = [n for n in to_draw if n not in hmdb_nodes + tf_nodes + target_nodes]

    # === Figure ===
    fig, ax = plt.subplots(figsize=(8, 6))
    edge_styles = get_edge_style_mapping()

    # === Draw nodes ===
    nx.draw_networkx_nodes(
        to_draw, pos,
        nodelist=tf_nodes,
        node_color="lightgreen",
        node_size=800,
        node_shape='o',
        ax=ax
    )
    nx.draw_networkx_nodes(
        to_draw, pos,
        nodelist=target_nodes,
        node_color="orange",
        node_size=800,
        node_shape='o',
        ax=ax
    )
    nx.draw_networkx_nodes(
        to_draw, pos,
        nodelist=bridge_nodes,
        node_color="lightgrey",
        node_size=700,
        node_shape='o',
        ax=ax
    )
    # Metabolites are represented only by their label boxes, not as separate nodes

    # === Draw edges ===
    for category, style in edge_styles.items():
        edges_of_category = [
            (u, v) for (u, v) in to_draw.edges()
            if edge_info.get((u, v), {}).get("category") == category
            or edge_info.get((v, u), {}).get("category") == category
        ]
        if not edges_of_category:
            continue

        if category == "Metabolic_pathway":
            # Draw line ending in a dot at the edge of the target node
            # Orient: metabolite -> target
            for u, v in edges_of_category:
                # Determine direction: metabolite should be source
                if u in hmdb_nodes:
                    source, target = u, v
                elif v in hmdb_nodes:
                    source, target = v, u
                else:
                    # If neither is metabolite, just use u,v
                    source, target = u, v
                
                p1 = np.array(pos[source])
                p2 = np.array(pos[target])
                vec = p2 - p1
                dist = np.linalg.norm(vec)
                if dist == 0:
                    continue
                vec /= dist
                
                # Adjust node radius based on node type
                # Metabolites are squares with size 900, others are circles with size 700-800
                if target in hmdb_nodes:
                    node_radius = 0.065  # Slightly larger for metabolites
                else:
                    node_radius = 0.055
                
                # Stop line at node boundary
                p2_adj = p2 - vec * node_radius
                
                # Draw the line
                ax.plot([p1[0], p2_adj[0]], [p1[1], p2_adj[1]],
                        color=style["color"], linewidth=style["width"], 
                        alpha=style["alpha"], zorder=1)
                
                # Place dot exactly at the node boundary
                dot_point = p2 - vec * node_radius
                ax.plot(dot_point[0], dot_point[1], "o",
                        color=style["color"], markersize=8, 
                        markerfacecolor=style["color"],
                        markeredgecolor='black', markeredgewidth=0.5,
                        alpha=style["alpha"], zorder=3)

        elif category == "Causal":
            # Draw arrows from metabolite to target
            for u, v in edges_of_category:
                # Determine direction: arrow should point from metabolite to target
                start, end = (u, v) if u in hmdb_nodes else (v, u)
                p1 = np.array(pos[start])
                p2 = np.array(pos[end])
                vec = p2 - p1
                dist = np.linalg.norm(vec)
                if dist == 0:
                    continue
                vec /= dist
                
                # Adjust for node sizes
                start_radius = 0.065 if start in hmdb_nodes else 0.055
                end_radius = 0.065 if end in hmdb_nodes else 0.055
                
                p1_adj = p1 + vec * start_radius
                p2_adj = p2 - vec * end_radius
                
                arrow = FancyArrowPatch(
                    p1_adj, p2_adj,
                    arrowstyle='-|>',
                    color=style["color"],
                    linewidth=style["width"],
                    alpha=style["alpha"],
                    mutation_scale=15,
                    connectionstyle='arc3,rad=0',
                    shrinkA=0, shrinkB=0,
                    zorder=2
                )
                ax.add_patch(arrow)

        else:
            # Draw simple edges for PPI, Ambiguous, and Unknown
            nx.draw_networkx_edges(
                to_draw, pos,
                edgelist=edges_of_category,
                edge_color=style["color"],
                style=style["style"],
                width=style["width"],
                alpha=style["alpha"],
                arrows=False,
                ax=ax
            )
    
    # === Labels ===
    metabolite_labels = {n: hmdb_to_name.get(n, n) for n in hmdb_nodes}
    nx.draw_networkx_labels(to_draw, pos, labels=metabolite_labels,
                            font_size=6, font_weight='bold',
                            bbox=dict(boxstyle='round,pad=0.4', fc='red', ec='none', alpha=0.7), ax=ax)
    other_labels = {n: n for n in to_draw if n not in hmdb_nodes}
    nx.draw_networkx_labels(to_draw, pos, labels=other_labels, font_size=5, font_weight='bold', ax=ax)

    # === Legends ===
    edge_legend_elements = create_edge_legend_by_category(ax, edge_styles, edge_info)
    node_legend_elements = create_node_legend(ax,
                                              has_metabolites=bool(hmdb_nodes),
                                              has_tfs=bool(tf_nodes),
                                              has_targets=bool(target_nodes),
                                              has_bridge=bool(bridge_nodes))
    legend_handles = edge_legend_elements + [Line2D([], [], color='none', label='')] + node_legend_elements
    ax.legend(handles=legend_handles, loc='upper left', bbox_to_anchor=(1.01, 1), fontsize=6,
              framealpha=0.9, borderpad=0.5, labelspacing=0.3, handlelength=1.5)

    # === Finalize ===
    plt.title(f'Module {module} - Subnetwork in LemonIte PKN\n'
              f'({len(to_draw.nodes())} nodes, {len(to_draw.edges())} edges)', fontsize=10)
    plt.axis('off')
    plt.tight_layout()

    os.makedirs('./Networks/subnetworks', exist_ok=True)
    plt.savefig(f'./Networks/subnetworks/graph_{module}_categorized_clean.png', dpi=200, bbox_inches='tight')
    plt.close()

    print_edge_statistics(edge_info)
    export_to_cytoscape_with_categories(to_draw, module, hmdb_to_name, TF_regulators, target_genes, edge_info, PKN_df)


# Update the main loop to pass both PKN DataFrame and NetworkX graph
for module in module2mets.keys():
    try:
        draw_subnetwork(
            module, 
            module2genes[module], 
            module2TFs[module], 
            module2mets[module],
            PKN,  # Pass DataFrame
            PKN.nx,  # Pass NetworkX graph
            name_to_hmdb
        )
    except KeyError:
        print(f'Module {module} not found in the mapping file')
        continue
    except Exception as e:
        print(f'An error occurred while processing module {module}: {e}')
        import traceback
        traceback.print_exc()
        continue

Module 0: 2 metabolites, 3 TFs, 88 targets.

=== Edge Statistics ===

By Category:
  PPI: 11
  Metabolic_pathway: 10

By Type:
  PPI: 11
  metabolite-gene: 10

By Source:
  STRING: 11
  Human1_GEM_dist2: 8
  Human1_GEM_dist1: 2

Cytoscape files with categorized edges saved for module 0:
  Edges: ./Networks/cytoscape/module_0_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_0_attributes.tsv
Module 1: 4 metabolites, 5 TFs, 71 targets.

=== Edge Statistics ===

By Category:
  PPI: 3
  Ambiguous: 2
  Metabolic_pathway: 1

By Type:
  PPI: 3
  metabolite-gene: 3

By Source:
  UniProtKB: 2
  STRING: 2
  BioGRID_genes: 1
  Human1_GEM_dist2: 1

Cytoscape files with categorized edges saved for module 1:
  Edges: ./Networks/cytoscape/module_1_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_1_attributes.tsv
Module 10: 4 metabolites, 4 TFs, 44 targets.

=== Edge Statistics ===

By Category:
  Ambiguous: 2
  PPI: 2
  Metabolic_pathway: 1

By Type:
  metabolite-gene: 3
  PPI: 2

By Source:
  UniProtKB: 2
  STRING: 2
  Human1_GEM_dist2: 1

Cytoscape files with categorized edges saved for module 10:
  Edges: ./Networks/cytoscape/module_10_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_10_attributes.tsv
Module 11: 2 metabolites, 4 TFs, 42 targets.

=== Edge Statistics ===

By Category:
  Metabolic_pathway: 8
  PPI: 6

By Type:
  metabolite-gene: 8
  PPI: 6

By Source:
  Human1_GEM_dist2: 7
  STRING: 4
  BioGRID_genes: 2
  Human1_GEM_dist1: 1

Cytoscape files with categorized edges saved for module 11:
  Edges: ./Networks/cytoscape/module_11_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_11_attributes.tsv
Module 12: 4 metabolites, 5 TFs, 144 targets.

=== Edge Statistics ===

By Category:
  Metabolic_pathway: 14
  PPI: 5

By Type:
  metabolite-gene: 14
  PPI: 5

By Source:
  Human1_GEM_dist2: 14
  BioGRID_genes: 4
  STRING: 1

Cytoscape files with categorized edges saved for module 12:
  Edges: ./Networks/cytoscape/module_12_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_12_attributes.tsv
Module 13: 4 metabolites, 4 TFs, 61 targets.

=== Edge Statistics ===

By Category:
  Metabolic_pathway: 2
  PPI: 2

By Type:
  metabolite-gene: 2
  PPI: 2

By Source:
  Human1_GEM_dist2: 2
  STRING: 1
  BioGRID_genes: 1

Cytoscape files with categorized edges saved for module 13:
  Edges: ./Networks/cytoscape/module_13_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_13_attributes.tsv
Module 14: 1 metabolites, 3 TFs, 48 targets.

=== Edge Statistics ===

By Category:
  PPI: 1
  Metabolic_pathway: 1

By Type:
  PPI: 1
  metabolite-gene: 1

By Source:
  STRING: 1
  Human1_GEM_dist2: 1

Cytoscape files with categorized edges saved for module 14:
  Edges: ./Networks/cytoscape/module_14_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_14_attributes.tsv
Module 15: 2 metabolites, 7 TFs, 41 targets.

=== Edge Statistics ===

By Category:
  PPI: 9
  Metabolic_pathway: 6

By Type:
  PPI: 9
  metabolite-gene: 6

By Source:
  STRING: 7
  Human1_GEM_dist2: 6
  BioGRID_genes: 2

Cytoscape files with categorized edges saved for module 15:
  Edges: ./Networks/cytoscape/module_15_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_15_attributes.tsv
Module 16: 4 metabolites, 5 TFs, 199 targets.
No valid connections for module 16.
Module 17: 2 metabolites, 8 TFs, 80 targets.

=== Edge Statistics ===

By Category:
  PPI: 9
  Metabolic_pathway: 4
  Causal: 1

By Type:
  PPI: 9
  metabolite-gene: 5

By Source:
  STRING: 8
  Human1_GEM_dist2: 4
  LINCS: 1
  BioGRID_genes: 1

Cytoscape files with categorized edges saved for module 17:
  Edges: ./Networks/cytoscape/module_17_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_17_attributes.tsv
Module 18: 2 metabolites, 7 TFs, 58 targets.

=== Edge Statistics ===

By Category:
  PPI: 21
  Metabolic_pathway: 14
  Ambiguous: 1

By Type:
  PPI: 21
  metabolite-gene: 15

By Source:
  Human1_GEM_dist2: 12
  BioGRID_genes: 11
  STRING: 10
  Human1_GEM_dist1: 2
  UniProtKB: 1

Cytoscape files with categorized edges saved for module 18:
  Edges: ./Networks/cytoscape/module_18_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_18_attributes.tsv
Module 19: 2 metabolites, 5 TFs, 73 targets.

=== Edge Statistics ===

By Category:
  Metabolic_pathway: 3
  PPI: 1

By Type:
  metabolite-gene: 3
  PPI: 1

By Source:
  Human1_GEM_dist2: 3
  STRING: 1

Cytoscape files with categorized edges saved for module 19:
  Edges: ./Networks/cytoscape/module_19_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_19_attributes.tsv
Module 2: 3 metabolites, 6 TFs, 83 targets.

=== Edge Statistics ===

By Category:
  Metabolic_pathway: 19
  PPI: 18
  Causal: 1

By Type:
  metabolite-gene: 20
  PPI: 18

By Source:
  Human1_GEM_dist2: 18
  STRING: 14
  BioGRID_genes: 4
  Human1_GEM_dist1: 1
  chEMBL: 1

Cytoscape files with categorized edges saved for module 2:
  Edges: ./Networks/cytoscape/module_2_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_2_attributes.tsv
Module 20: 2 metabolites, 7 TFs, 35 targets.

=== Edge Statistics ===

By Category:
  Metabolic_pathway: 10
  PPI: 10

By Type:
  metabolite-gene: 10
  PPI: 10

By Source:
  Human1_GEM_dist2: 10
  STRING: 8
  BioGRID_genes: 2

Cytoscape files with categorized edges saved for module 20:
  Edges: ./Networks/cytoscape/module_20_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_20_attributes.tsv
Module 21: 4 metabolites, 7 TFs, 29 targets.

=== Edge Statistics ===

By Category:
  Metabolic_pathway: 20
  PPI: 17
  Ambiguous: 1

By Type:
  metabolite-gene: 21
  PPI: 17

By Source:
  Human1_GEM_dist2: 19
  STRING: 11
  BioGRID_genes: 6
  UniProtKB: 1
  Human1_GEM_dist1: 1

Cytoscape files with categorized edges saved for module 21:
  Edges: ./Networks/cytoscape/module_21_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_21_attributes.tsv
Module 23: 3 metabolites, 6 TFs, 44 targets.
No valid connections for module 23.
Module 24: 4 metabolites, 5 TFs, 24 targets.

=== Edge Statistics ===

By Category:
  PPI: 4
  Metabolic_pathway: 4

By Type:
  PPI: 4
  metabolite-gene: 4

By Source:
  STRING: 4
  Human1_GEM_dist2: 4

Cytoscape files with categorized edges saved for module 24:
  Edges: ./Networks/cytoscape/module_24_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_24_attributes.tsv
Module 25: 1 metabolites, 7 TFs, 70 targets.
No valid connections for module 25.
Module 26: 3 metabolites, 8 TFs, 31 targets.

=== Edge Statistics ===

By Category:
  PPI: 16
  Metabolic_pathway: 9

By Type:
  PPI: 16
  metabolite-gene: 9

By Source:
  Human1_GEM_dist2: 9
  STRING: 8
  BioGRID_genes: 8

Cytoscape files with categorized edges saved for module 26:
  Edges: ./Networks/cytoscape/module_26_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_26_attributes.tsv
Module 27: 1 metabolites, 1 TFs, 20 targets.
No valid connections for module 27.
Module 29: 1 metabolites, 3 TFs, 21 targets.
No valid connections for module 29.
Module 3: 3 metabolites, 5 TFs, 53 targets.

=== Edge Statistics ===

By Category:
  PPI: 4
  Metabolic_pathway: 2

By Type:
  PPI: 4
  metabolite-gene: 2

By Source:
  BioGRID_genes: 3
  Human1_GEM_dist2: 2
  STRING: 1

Cytoscape files with categorized edges saved for module 3:
  Edges: ./Networks/cytoscape/module_3_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_3_attributes.tsv
Module 30: 3 metabolites, 4 TFs, 63 targets.

=== Edge Statistics ===

By Category:
  Metabolic_pathway: 8
  PPI: 8

By Type:
  metabolite-gene: 8
  PPI: 8

By Source:
  Human1_GEM_dist2: 8
  STRING: 7
  BioGRID_genes: 1

Cytoscape files with categorized edges saved for module 30:
  Edges: ./Networks/cytoscape/module_30_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_30_attributes.tsv
Module 31: 1 metabolites, 2 TFs, 22 targets.
No valid connections for module 31.
Module 33: 2 metabolites, 2 TFs, 25 targets.

=== Edge Statistics ===

By Category:
  PPI: 3
  Metabolic_pathway: 3

By Type:
  PPI: 3
  metabolite-gene: 3

By Source:
  STRING: 2
  Human1_GEM_dist2: 2
  Human1_GEM_dist1: 1
  BioGRID_genes: 1

Cytoscape files with categorized edges saved for module 33:
  Edges: ./Networks/cytoscape/module_33_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_33_attributes.tsv
Module 34: 1 metabolites, 7 TFs, 28 targets.

=== Edge Statistics ===

By Category:
  PPI: 3
  Metabolic_pathway: 3

By Type:
  PPI: 3
  metabolite-gene: 3

By Source:
  Human1_GEM_dist2: 3
  STRING: 2
  BioGRID_genes: 1

Cytoscape files with categorized edges saved for module 34:
  Edges: ./Networks/cytoscape/module_34_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_34_attributes.tsv
Module 35 not found in the mapping file
Module 36: 3 metabolites, 3 TFs, 24 targets.

=== Edge Statistics ===

By Category:
  Metabolic_pathway: 10
  PPI: 4

By Type:
  metabolite-gene: 10
  PPI: 4

By Source:
  Human1_GEM_dist2: 10
  BioGRID_genes: 4

Cytoscape files with categorized edges saved for module 36:
  Edges: ./Networks/cytoscape/module_36_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_36_attributes.tsv
Module 37: 2 metabolites, 4 TFs, 18 targets.

=== Edge Statistics ===

By Category:
  PPI: 2
  Ambiguous: 1

By Type:
  PPI: 2
  metabolite-gene: 1

By Source:
  STRING: 1
  UniProtKB: 1
  BioGRID_genes: 1

Cytoscape files with categorized edges saved for module 37:
  Edges: ./Networks/cytoscape/module_37_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_37_attributes.tsv
Module 39: 3 metabolites, 3 TFs, 14 targets.

=== Edge Statistics ===

By Category:
  PPI: 4
  Ambiguous: 2
  Metabolic_pathway: 1

By Type:
  PPI: 4
  metabolite-gene: 3

By Source:
  STRING: 4
  UniProtKB: 2
  Human1_GEM_dist2: 1

Cytoscape files with categorized edges saved for module 39:
  Edges: ./Networks/cytoscape/module_39_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_39_attributes.tsv
Module 4: 4 metabolites, 3 TFs, 60 targets.

=== Edge Statistics ===

By Category:
  PPI: 5
  Metabolic_pathway: 4
  Ambiguous: 1

By Type:
  metabolite-gene: 5
  PPI: 5

By Source:
  Human1_GEM_dist2: 4
  STRING: 4
  UniProtKB: 1
  BioGRID_genes: 1

Cytoscape files with categorized edges saved for module 4:
  Edges: ./Networks/cytoscape/module_4_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_4_attributes.tsv
Module 40: 2 metabolites, 5 TFs, 13 targets.

=== Edge Statistics ===

By Category:
  PPI: 6
  Ambiguous: 1
  Metabolic_pathway: 1

By Type:
  PPI: 6
  metabolite-gene: 2

By Source:
  BioGRID_genes: 6
  UniProtKB: 1
  Human1_GEM_dist2: 1

Cytoscape files with categorized edges saved for module 40:
  Edges: ./Networks/cytoscape/module_40_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_40_attributes.tsv
Module 41: 2 metabolites, 5 TFs, 17 targets.
No valid connections for module 41.
Module 42: 1 metabolites, 5 TFs, 17 targets.
No valid connections for module 42.
Module 43: 1 metabolites, 7 TFs, 15 targets.

=== Edge Statistics ===

By Category:
  PPI: 10
  Metabolic_pathway: 5

By Type:
  PPI: 10
  metabolite-gene: 5

By Source:
  STRING: 6
  Human1_GEM_dist2: 5
  BioGRID_genes: 4

Cytoscape files with categorized edges saved for module 43:
  Edges: ./Networks/cytoscape/module_43_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_43_attributes.tsv
Module 44: 1 metabolites, 2 TFs, 12 targets.

=== Edge Statistics ===

By Category:
  PPI: 1
  Metabolic_pathway: 1

By Type:
  PPI: 1
  metabolite-gene: 1

By Source:
  BioGRID_genes: 1
  Human1_GEM_dist2: 1

Cytoscape files with categorized edges saved for module 44:
  Edges: ./Networks/cytoscape/module_44_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_44_attributes.tsv
Module 45: 1 metabolites, 3 TFs, 17 targets.
No valid connections for module 45.
Module 46: 3 metabolites, 6 TFs, 11 targets.

=== Edge Statistics ===

By Category:
  Metabolic_pathway: 7
  PPI: 6

By Type:
  metabolite-gene: 7
  PPI: 6

By Source:
  Human1_GEM_dist2: 6
  STRING: 4
  BioGRID_genes: 2
  Human1_GEM_dist1: 1

Cytoscape files with categorized edges saved for module 46:
  Edges: ./Networks/cytoscape/module_46_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_46_attributes.tsv
Module 47: 3 metabolites, 4 TFs, 34 targets.
No valid connections for module 47.
Module 48: 1 metabolites, 3 TFs, 11 targets.

=== Edge Statistics ===

By Category:
  PPI: 1
  Metabolic_pathway: 1

By Type:
  PPI: 1
  metabolite-gene: 1

By Source:
  STRING: 1
  Human1_GEM_dist2: 1

Cytoscape files with categorized edges saved for module 48:
  Edges: ./Networks/cytoscape/module_48_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_48_attributes.tsv
Module 5: 1 metabolites, 5 TFs, 66 targets.

=== Edge Statistics ===

By Category:
  PPI: 8
  Metabolic_pathway: 4

By Type:
  PPI: 8
  metabolite-gene: 4

By Source:
  STRING: 5
  Human1_GEM_dist2: 4
  BioGRID_genes: 3

Cytoscape files with categorized edges saved for module 5:
  Edges: ./Networks/cytoscape/module_5_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_5_attributes.tsv
Module 50: 1 metabolites, 3 TFs, 13 targets.

=== Edge Statistics ===

By Category:
  PPI: 6
  Metabolic_pathway: 3

By Type:
  PPI: 6
  metabolite-gene: 3

By Source:
  STRING: 4
  Human1_GEM_dist2: 3
  BioGRID_genes: 2

Cytoscape files with categorized edges saved for module 50:
  Edges: ./Networks/cytoscape/module_50_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_50_attributes.tsv
Module 51: 2 metabolites, 3 TFs, 14 targets.

=== Edge Statistics ===

By Category:
  PPI: 3
  Metabolic_pathway: 2

By Type:
  PPI: 3
  metabolite-gene: 2

By Source:
  STRING: 2
  Human1_GEM_dist2: 2
  BioGRID_genes: 1

Cytoscape files with categorized edges saved for module 51:
  Edges: ./Networks/cytoscape/module_51_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_51_attributes.tsv
Module 53: 4 metabolites, 6 TFs, 10 targets.

=== Edge Statistics ===

By Category:
  PPI: 6
  Metabolic_pathway: 4

By Type:
  PPI: 6
  metabolite-gene: 4

By Source:
  STRING: 4
  Human1_GEM_dist2: 3
  BioGRID_genes: 2
  Human1_GEM_dist1: 1

Cytoscape files with categorized edges saved for module 53:
  Edges: ./Networks/cytoscape/module_53_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_53_attributes.tsv
Module 55: 1 metabolites, 6 TFs, 40 targets.
No valid connections for module 55.
Module 56: 2 metabolites, 5 TFs, 10 targets.
No valid connections for module 56.
Module 57: 2 metabolites, 7 TFs, 11 targets.

=== Edge Statistics ===

By Category:
  PPI: 6
  Metabolic_pathway: 4
  Ambiguous: 1

By Type:
  PPI: 6
  metabolite-gene: 5

By Source:
  STRING: 6
  Human1_GEM_dist2: 4
  BioGRID: 1

Cytoscape files with categorized edges saved for module 57:
  Edges: ./Networks/cytoscape/module_57_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_57_attributes.tsv
Module 59: 3 metabolites, 7 TFs, 21 targets.

=== Edge Statistics ===

By Category:
  PPI: 17
  Metabolic_pathway: 11
  Ambiguous: 1

By Type:
  PPI: 17
  metabolite-gene: 12

By Source:
  Human1_GEM_dist2: 11
  BioGRID_genes: 10
  STRING: 7
  UniProtKB: 1

Cytoscape files with categorized edges saved for module 59:
  Edges: ./Networks/cytoscape/module_59_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_59_attributes.tsv
Module 6: 3 metabolites, 5 TFs, 155 targets.

=== Edge Statistics ===

By Category:
  Metabolic_pathway: 16
  PPI: 15

By Type:
  metabolite-gene: 16
  PPI: 15

By Source:
  Human1_GEM_dist2: 14
  STRING: 13
  Human1_GEM_dist1: 2
  BioGRID_genes: 2

Cytoscape files with categorized edges saved for module 6:
  Edges: ./Networks/cytoscape/module_6_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_6_attributes.tsv
Module 60: 1 metabolites, 3 TFs, 10 targets.
No valid connections for module 60.
Module 61: 1 metabolites, 5 TFs, 10 targets.
No valid connections for module 61.
Module 62: 2 metabolites, 5 TFs, 10 targets.

=== Edge Statistics ===

By Category:
  PPI: 10
  Metabolic_pathway: 9

By Type:
  PPI: 10
  metabolite-gene: 9

By Source:
  Human1_GEM_dist2: 9
  STRING: 9
  BioGRID_genes: 1

Cytoscape files with categorized edges saved for module 62:
  Edges: ./Networks/cytoscape/module_62_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_62_attributes.tsv
Module 7: 1 metabolites, 8 TFs, 129 targets.

=== Edge Statistics ===

By Category:
  Metabolic_pathway: 8
  PPI: 7

By Type:
  metabolite-gene: 8
  PPI: 7

By Source:
  Human1_GEM_dist2: 8
  BioGRID_genes: 4
  STRING: 3

Cytoscape files with categorized edges saved for module 7:
  Edges: ./Networks/cytoscape/module_7_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_7_attributes.tsv
Module 8: 3 metabolites, 6 TFs, 37 targets.
No valid connections for module 8.
Module 9: 3 metabolites, 5 TFs, 106 targets.

=== Edge Statistics ===

By Category:
  Metabolic_pathway: 3
  PPI: 3

By Type:
  metabolite-gene: 3
  PPI: 3

By Source:
  Human1_GEM_dist2: 3
  BioGRID_genes: 2
  STRING: 1

Cytoscape files with categorized edges saved for module 9:
  Edges: ./Networks/cytoscape/module_9_edges_categorized.tsv
  Attributes: ./Networks/cytoscape/module_9_attributes.tsv